const Map<int, String> MIDI_INSTRUMENTS = {
  // https://en.wikipedia.org/wiki/General_MIDI#Program_change_events
//Piano
  1: "Acoustic Grand Piano or Piano 1",
  2: "Bright Acoustic Piano or Piano 2",
  3: "Electric Grand Piano or Piano 3 (usually modeled after Yamaha CP-70)",
  4: "Honky-tonk Piano",
  5: "Electric Piano 1 (usually a Rhodes or Wurlitzer piano)",
  6: "Electric Piano 2 (usually an FM piano patch, often chorused)",
  7: "Harpsichord (often with a fixed velocity level)",
  8: "Clavinet",
// Chromatic Percussion
  9: "Celesta",
  10: "Glockenspiel",
  11: "Music Box",
  12: "Vibraphone",
  13: "Marimba",
  14: "Xylophone",
  15: "Tubular Bells",
  16: "Dulcimer or Santoor",
// Organ
  17: "Drawbar Organ or Organ 1",
  18: "Percussive Organ or Organ 2",
  19: "Rock Organ or Organ 3",
  20: "Church Organ",
  21: "Reed Organ",
  22: "Accordion",
  23: "Harmonica",
  24: "Bandoneon or Tango Accordion",
// Guitar
// In most synthesizer interpretations, guitar and bass sounds are set an octave lower than other instruments.
  25: 'Acoustic Guitar (nylon)',
  26: 'Acoustic Guitar (steel)',
  27: 'Electric Guitar (jazz)',
  28: 'Electric Guitar (clean, often chorused, resembling a Stratocaster run through a Roland Jazz Chorus amplifier)',
  29: 'Electric Guitar (muted)',
  30: 'Overdriven Guitar',
  31: 'Distortion Guitar',
  32: 'Guitar Harmonics',
// Bass
  33: 'Acoustic Bass',
  34: 'Electric Bass (finger)',
  35: 'Electric Bass (picked)',
  36: 'Fretless Bass',
  37: 'Slap Bass 1',
  38: 'Slap Bass 2',
  39: 'Synth Bass 1',
  40: 'Synth Bass 2',
// Strings
  41: 'Violin',
  42: 'Viola',
  43: 'Cello',
  44: 'Contrabass',
  45: 'Tremolo Strings',
  46: 'Pizzicato Strings',
  47: 'Orchestral Harp',
  48: 'Timpani',
// Ensemble
  49: 'String Ensemble 1 (often in marcato)',
  50: 'String Ensemble 2 (slower attack than String Ensemble 1)',
  51: 'Synth Strings 1',
  52: 'Synth Strings 2',
  53: 'Choir Aahs',
  54: 'Voice Oohs (or Doos)',
  55: 'Synth Voice or Synth Choir',
  56: 'Orchestra Hit',
// Brass
  57: 'Trumpet',
  58: 'Trombone',
  59: 'Tuba',
  60: 'Muted Trumpet',
  61: 'French Horn',
  62: 'Brass Section',
  63: 'Synth Brass 1',
  64: 'Synth Brass 2',
// Reed
  65: 'Soprano Sax',
  66: 'Alto Sax',
  67: 'Tenor Sax',
  68: 'Baritone Sax',
  69: 'Oboe',
  70: 'English Horn',
  71: 'Bassoon',
  72: 'Clarinet',
// Pipe
  73: 'Piccolo',
  74: 'Flute',
  75: 'Recorder',
  76: 'Pan Flute',
  77: 'Blown bottle',
  78: 'Shakuhachi',
  79: 'Whistle',
  80: 'Ocarina',
// Synth Lead
  81: 'Lead 1 (square, often chorused)',
  82: 'Lead 2 (sawtooth or saw, often chorused)',
  83: 'Lead 3 (calliope, usually resembling a woodwind)',
  84: 'Lead 4 (chiff)',
  85: 'Lead 5 (charang, a guitar-like lead)',
  86: 'Lead 6 (voice, derived from "synth voice" with faster attack)',
  87: 'Lead 7 (fifths)',
  88: 'Lead 8 (bass and lead or solo lead or sometimes mistakenly called "brass and lead")',
// Synth Pad
  89: 'Pad 1 (new age, pad stacked with a bell, often derived from "Fantasia" patch from Roland D-50)',
  90: 'Pad 2 (warm, a mellower pad with slow attack)',
  91: 'Pad 3 (polysynth or poly, a saw-like percussive pad resembling an early 1980s polyphonic synthesizer)',
  92: 'Pad 4 (choir, identical to "synth voice" with longer decay)',
  93: 'Pad 5 (bowed glass or bowed, a sound resembling a glass harmonica)',
  94: 'Pad 6 (metallic, often created from a piano or guitar sample played with the attack removed)',
  95: 'Pad 7 (halo, choir-like pad, often with a filter effect)',
  96: 'Pad 8 (sweep, pad with a pronounced "wah" filter effect)',
// Synth Effects
  97: 'FX 1 (rain, a bright pluck with echoing pulses that decreases in pitch)',
  98: 'FX 2 (soundtrack, a bright perfect fifth pad)',
  99: 'FX 3 (crystal, a synthesized bell sound)',
  100: 'FX 4 (atmosphere, usually a classical guitar-like sound)',
  101: 'FX 5 (brightness, bright pad stacked with choir or bell)',
  102: 'FX 6 (goblins, a slow-attack pad with chirping or murmuring sounds)',
  103: 'FX 7 (echoes or echo drops, similar to "rain")',
  104: 'FX 8 (sci-fi or star theme, usually an electric guitar-like pad)',
// Ethnic
  105: "Sitar",
  106: "Banjo",
  107: "Shamisen",
  108: "Koto",
  109: "Kalimba",
  110: "Bag pipe",
  111: "Fiddle",
  112: "Shanai",
// Percussive
  113: "Tinkle Bell",
  114: "Agogô or cowbell",
  115: "Steel Drums",
  116: "Woodblock",
  117: "Taiko Drum or Surdo",
  118: "Melodic Tom",
  119:
      "Synth Drum (a synthesized tom-tom derived from Simmons electronic drum)",
  120: "Reverse Cymbal",
// Sound Effects
  121: "Guitar Fret Noise",
  122: "Breath Noise",
  123: "Seashore",
  124: "Bird Tweet",
  125: "Telephone Ring",
  126: "Helicopter",
  127: "Applause",
  128: "Gunshot",
};

const Map<int, String> MIDI_PERCUSSIONS = {
  35: 'Acoustic Bass Drum or Low Bass Drum',
  36: 'Electric Bass Drum or High Bass Drum',
  37: 'Side Stick',
  38: 'Acoustic Snare',
  39: 'Hand Clap',
  40: 'Electric Snare or Rimshot',
  41: 'Low Floor Tom',
  42: 'Closed Hi-hat',
  43: 'High Floor Tom',
  44: 'Pedal Hi-hat',
  45: 'Low Tom',
  46: 'Open Hi-hat',
  47: 'Low-Mid Tom',
  48: 'High-Mid Tom',
  49: 'Crash Cymbal 1',
  50: 'High Tom',
  51: 'Ride Cymbal 1',
  52: 'Chinese Cymbal',
  53: 'Ride Bell',
  54: 'Tambourine',
  55: 'Splash Cymbal',
  56: 'Cowbell',
  57: 'Crash Cymbal 2',
  58: 'Vibraslap',
  59: 'Ride Cymbal 2',
  60: 'High Bongo',
  61: 'Low Bongo',
  62: 'Mute High Conga',
  63: 'Open High Conga',
  64: 'Low Conga',
  65: 'High Timbale',
  66: 'Low Timbale',
  67: 'High Agogô',
  68: 'Low Agogô',
  69: 'Cabasa',
  70: 'Maracas',
  71: 'Short Whistle',
  72: 'Long Whistle',
  73: 'Short Güiro',
  74: 'Long Güiro',
  75: 'Claves',
  76: 'High Woodblock',
  77: 'Low Woodblock',
  78: 'Mute Cuíca',
  79: 'Open Cuíca',
  80: 'Mute Triangle',
  81: 'Open Triangle',
};
