part of 'about.dart';

const List<String> PROJECTLEAD = ['Mike \'MikeBi\' B.', 'Thomas \'TMZ\' Z.'];

const List<String> DEVELOPMENT = [
  'Mike \'MikeBi\' B.', 'Thomas \'TMZ\' Z.', 'Mark \'S-Man42\' Lorenz', 'Olli \'Rinser\''
];

const List<String> SPECIALTHANKS = ['Daniel \'Eisbehr\' K. (Maintainer GCC)'];

const List<String> TESTS = [ 'Andy \'Puma66\' (Special Support)', 'Maria \'Nebelsturm\''];

const List<String> MANUALCREATORS = ['Andreas \'TeamBirdy2404\'', 'Thomas \'TMZ\' Z.', 'Marcia \'Linsty\''];

const List<String> MISC = ['Henrike \'69and71\' (Translations)'];

const List<String> CONTRIBUTORS = [
  '\xc4ggsb\xe4rde (Symbol Tables)',
  'andre0707 (Day1976 Code)',
  'capoaira (Code)',
  'Dennis \'dennistreysa\' (Code)',
  'Frank \'Wizardland\' (podKst.de) (Hardware)',
  'Geo-Link (Hardware & Symbol Tables)',
  'Karl B. (Coords Algorithms)',
  'Ludovic \'LudoO\' Valente (Code & Translation FR)',
  'Michael D. (Symbol Tables)',
  'Nina \'nike1972\' G. (Nina\'s Schmierblo(g)ck) (Manual)',
  'moenk (GK Coords)',
  'radioscout (Research)',
  'Schnatt (Symbol Tables)',
  'Udo J. (Code)',
  'wollpirat (Food, Tea & more)'
];

const List<String> TRANSLATORS = [
  'alantheandroid (IT)',
  'alexgonc (PT, ES)',
  'bimsor (DK)',
  'Cavit A. (TR)',
  'crazedllama (KO)',
  'DrakeZero (ES)',
  'drobec (SK)',
  'emrszon (ES)',
  'hakuchi (IT)',
  '69and71 (NL, SV)',
  'Igor Č. (SK)',
  'j_janus (PL)',
  'Joao F. (PT)',
  'Johan-V (NL)',
  'juroot (SK)',
  'MAJ (ES)',
  'Martanal (CZ)',
  'n3oklan (CZ)',
  'Paul Z. (NL)',
  'Paweł B. (PL)',
  'proXmiii (SK)',
  'przematcr (PL)',
  'QouiZ (EL)',
  'S182 (IT)',
  'Silvia O. (SK)',
  'tkemer (EL)',
  'Todclerc (NL)',
  'verturin (FR, IT)',
  'vike91 (FI)',
  'Vojta_ (CZ)',
  'Willa_Lecznica (PL)',
  'Xoyn (RU)',
];

const List<String> TESTER = [
  '4-Everus',
  '83_Seth',
  'Amelie2401',
  'Andreas E.',
  'Andreas L.',
  'baer2006',
  'Bleg1966',
  'Cycle73',
  'Dawn T.',
  'Don Rodolphos',
  'Felix Z.',
  'ferrrix',
  'Filu \'Aye, Käppn!\' 43 & Stormi \'Aaarrh\' 2061',
  'finding tresor',
  'Flosphor',
  'Franz K.',
  'Freakyfinder',
  'geo_aug',
  'GrafZahl75',
  'Headbanger-Berlin',
  'hermannslaender',
  'hwi',
  'Isidore S.',
  'JanRei',
  'Johannes C.',
  'Jonas M.',
  'kinderarzt',
  'Klumpenkukuk',
  'Lue',
  'LupiMus',
  'Lutz \'DL3BZZ\'',
  'mahoplus',
  'Markus M.',
  'Martin Sch.',
  'Martina F.',
  'mgo',
  'MicDie',
  'Michael St.',
  'Mondlinger',
  'MrDosinger & MsDosinger',
  'mister-rage',
  'musketon',
  'Niki R.',
  'Palk \'geogedoens.de\'',
  'Pamakaru',
  'Pascal M.',
  'Peter S.-H.',
  'radlerandi',
  'realMrTom',
  'Richard M.',
  'Roland Rosenfeld',
  'schatzi-s',
  'Sechsfüssler',
  'Skarden',
  'Stefan J.',
  'Stefan K.',
  'SzpiegDonPedro',
  'Team kesteri',
  'Thomas B.',
  'tebarius',
  'tomcat06',
  'trekkiefreak76',
  'Vlad_Tepes',
  'Vyrembi',
  'waldstadt',
  'WeinWalker',
  'WingsAndTales',
  'zoRRo'
];
