part of 'package:gc_wizard/tools/images_and_files/id3_tag/logic/id3_tag.dart';

// Genre list in ID3v1
// https://en.wikipedia.org/wiki/List_of_ID3v1_genres
// https://web.archive.org/web/20151121080450/http://id3.org/id3v2.3.0#Appendix_A_-_Genre_List_from_ID3v1
const Map<int, String> genreList = {
  0:'Blues',
  1:'Classic Rock',
  2:'Country',
  3:'Dance',
  4:'Disco',
  5:'Funk',
  6:'Grunge',
  7:'Hip-Hop',
  8:'Jazz',
  9:'Metal',
  10:'New Age',
  11:'Oldies',
  12:'Other',
  13:'Pop',
  14:'R&B',
  15:'Rap',
  16:'Reggae',
  17:'Rock',
  18:'Techno',
  19:'Industrial',
  20:'Alternative',
  21:'Ska',
  22:'Death Metal',
  23:'Pranks',
  24:'Soundtrack',
  25:'Euro-Techno',
  26:'Ambient',
  27:'Trip-Hop',
  28:'Vocal',
  29:'Jazz+Funk',
  30:'Fusion',
  31:'Trance',
  32:'Classical',
  33:'Instrumental',
  34:'Acid',
  35:'House',
  36:'Game',
  37:'Sound clip',
  38:'Gospel',
  39:'Noise',
  40:'AlternRock',
  41:'Bass',
  42:'Soul',
  43:'Punk',
  44:'Space',
  45:'Meditative',
  46:'Instrumental Pop',
  47:'Instrumental Rock',
  48:'Ethnic',
  49:'Gothic',
  50:'Darkwave',
  51:'Techno-Industrial',
  52:'Electronic',
  53:'Pop-Folk',
  54:'Eurodance',
  55:'Dream',
  56:'Southern Rock',
  57:'Comedy',
  58:'Cult',
  59:'Gangsta',
  60:'Top 40',
  61:'Christian Rap',
  62:'Pop/Funk',
  63:'Jungle',
  64:'Native American',
  65:'Cabaret',
  66:'New Wave',
  67:'Psychedelic',
  68:'Rave',
  69:'Showtunes',
  70:'Trailer',
  71:'Lo-Fi',
  72:'Tribal',
  73:'Acid Punk',
  74:'Acid Jazz',
  75:'Polka',
  76:'Retro',
  77:'Musical',
  78:'Rock & Roll',
  79:'Hard Rock',
  // The following genres are Winamp extensions
  // 80 - 191
  80:'Folk',
  81:'Folk-Rock',
  82:'National Folk',
  83:'Swing',
  84:'Fast Fusion',
  85:'Bebob',
  86:'Latin',
  87:'Revival',
  88:'Celtic',
  89:'Bluegrass',
  90:'Avantgarde',
  91:'Gothic Rock',
  92:'Progressive Rock',
  93:'Psychedelic Rock',
  94:'Symphonic Rock',
  95:'Slow Rock',
  96:'Big Band',
  97:'Chorus',
  98:'Easy Listening',
  99:'Acoustic',
  100:'Humour',
  101:'Speech',
  102:'Chanson',
  103:'Opera',
  104:'Chamber Music',
  105:'Sonata',
  106:'Symphony',
  107:'Booty Bass',
  108:'Primus',
  109:'Porn Groove',
  110:'Satire',
  111:'Slow Jam',
  112:'Club',
  113:'Tango',
  114:'Samba',
  115:'Folklore',
  116:'Ballad',
  117:'Power Ballad',
  118:'Rhythmic Soul',
  119:'Freestyle',
  120:'Duet',
  121:'Punk Rock',
  122:'Drum Solo',
  123:'A capella',
  124:'Euro-House',
  125:'Dance Hall',
  126:'Goa music',
  127:'Drum & bass',
  128:'Club-house',
  129:'Hardcore techno',
  130:'Terror',
  131:'Indie',
  132:'Britpop',
  133:'Negerpunk',
  134:'Polsk punk',
  135:'Beat',
  136:'Christian gangsta rap',
  137:'Heavy metal',
  138:'Black metal',
  139:'Crossover',
  140:'Contemporary Christian',
  141:'Christian rock',
  142:'Merengue',
  143:'Salsa',
  144:'Thrash metal',
  145:'Anime',
  146:'Jpop',
  147:'Synthpop',
  148:'Christmas',
  149:'Art rock',
  150:'Baroque',
  151:'Bhangra',
  152:'Big beat',
  153:'Breakbeat',
  154:'Chillout',
  155:'Downtempo',
  156:'Dub',
  157:'EBM',
  158:'Eclectic',
  159:'Electro',
  160:'Electroclash',
  161:'Emo',
  162:'Experimental',
  163:'Garage',
  164:'Global',
  165:'IDM',
  166:'Illbient',
  167:'Industro-Goth',
  168:'Jam Band',
  169:'Krautrock',
  170:'Leftfield',
  171:'Lounge',
  172:'Math rock',
  173:'New romantic',
  174:'Nu-breakz',
  175:'Post-punk',
  176:'Post-rock',
  177:'Psytrance',
  178:'Shoegaze',
  179:'Space rock',
  180:'Trop rock',
  181:'World music',
  182:'Neoclassical',
  183:'Audiobook',
  184:'Audio theatre',
  185:'Neue Deutsche Welle',
  186:'Podcast',
  187:'Indie rock',
  188:'G-Funk',
  189:'Dubstep',
  190:'Garage rock',
  191:'Psybient',
};

final GENRE = switchMapKeyValue(genreList);

const Map<String, String> frameV2p2Map = {
  'BUF': 'Recommended buffer size',
  'CNT': 'Play counter',
  'COM': 'Comments',
  'CRA': 'Audio encryption',
  'CRM': 'Encrypted meta frame',
  'ETC': 'Event timing codes',
  'EQU': 'Equalization',
  'GEO': 'General encapsulated object',
  'IPL': 'Involved people list',
  'LNK': 'Linked information',
  'MCI': 'Music CD Identifier',
  'MLL': 'MPEG location lookup table',
  'PIC': 'Attached picture',
  'POP': 'Popularimeter',
  'REV': 'Reverb',
  'RVA': 'Relative volume adjustment',
  'SLT': 'Synchronized lyric/text',
  'STC': 'Synced tempo codes',
  'TAL': 'Album/Movie/Show title',
  'TBP': 'BPM (Beats Per Minute)',
  'TCM': 'Composer',
  'TCO': 'Content type',
  'TCR': 'Copyright message',
  'TDA': 'Date',
  'TDY': 'Playlist delay',
  'TEN': 'Encoded by',
  'TFT': 'File type',
  'TIM': 'Time',
  'TKE': 'Initial key',
  'TLA': 'Language(s)',
  'TLE': 'Length',
  'TMT': 'Media type',
  'TOA': 'Original artist(s)/performer(s)',
  'TOF': 'Original filename',
  'TOL': 'Original Lyricist(s)/text writer(s)',
  'TOR': 'Original release year',
  'TOT': 'Original album/Movie/Show title',
  'TP1': 'Lead artist(s)/Lead performer(s)/Soloist(s)/Performing group',
  'TP2': 'Band/Orchestra/Accompaniment',
  'TP3': 'Conductor/Performer refinement',
  'TP4': 'Interpreted, remixed, or otherwise modified by',
  'TPA': 'Part of a set',
  'TPB': 'Publisher',
  'TRC': 'ISRC (International Standard Recording Code)',
  'TRD': 'Recording dates',
  'TRK': 'Track number/Position in set',
  'TSI': 'Size',
  'TSS': 'Software/hardware and settings used for encoding',
  'TT1': 'Content group description',
  'TT2': 'Title/Songname/Content description',
  'TT3': 'Subtitle/Description refinement',
  'TXT': 'Lyricist/text writer',
  'TXX': 'User defined text information frame',
  'TYE': 'Year',
  'UFI': 'Unique file identifier',
  'ULT': 'Unsychronized lyric/text transcription',
  'WAF': 'Official audio file webpage',
  'WAR': 'Official artist/performer webpage',
  'WAS': 'Official audio source webpage',
  'WCM': 'Commercial information',
  'WCP': 'Copyright/Legal information',
  'WPB': 'Publishers official webpage',
  'WXX': 'User defined URL link frame',
};

// https://id3.org/d3v2.3.0
const Map<String, String> frameV2p3Map = {
  'AENC': 'Audio encryption',
  'APIC': 'Attached picture',
  'COMM': 'Comments',
  'COMR': 'Commercial frame',
  'ENCR': 'Encryption method registration',
  'EQUA': 'Equalization',
  'ETCO': 'Event timing codes',
  'GEOB': 'General encapsulated object',
  'GRID': 'Group identification registration',
  'IPLS': 'Involved people list',
  'LINK': 'Linked information',
  'MCDI': 'Music CD identifier',
  'MLLT': 'MPEG location lookup table',
  'OWNE': 'Ownership frame',
  'PRIV': 'Private frame',
  'PCNT': 'Play counter',
  'POPM': 'Popularimeter',
  'POSS': 'Position synchronisation frame',
  'RBUF': 'Recommended buffer size',
  'RVAD': 'Relative volume adjustment',
  'RVRB': 'Reverb',
  'SYLT': 'Synchronized lyric/text',
  'SYTC': 'Synchronized tempo codes',
  'TALB': 'Album/Movie/Show title',
  'TBPM': 'BPM (beats per minute)',
  'TCOM': 'Composer',
  'TCON': 'Content type',
  'TCOP': 'Copyright message',
  'TDAT': 'Date',
  'TDLY': 'Playlist delay',
  'TENC': 'Encoded by',
  'TEXT': 'Lyricist/Text writer',
  'TFLT': 'File type',
  'TIME': 'Time',
  'TIT1': 'Content group description',
  'TIT2': 'Title/songname/content description',
  'TIT3': 'Subtitle/Description refinement',
  'TKEY': 'Initial key',
  'TLAN': 'Language(s)',
  'TLEN': 'Length',
  'TMED': 'Media type',
  'TOAL': 'Original album/movie/show title',
  'TOFN': 'Original filename',
  'TOLY': 'Original lyricist(s)/text writer(s)',
  'TOPE': 'Original artist(s)/performer(s)',
  'TORY': 'Original release year',
  'TOWN': 'File owner/licensee',
  'TPE1': 'Lead performer(s)/Soloist(s)',
  'TPE2': 'Band/orchestra/accompaniment',
  'TPE3': 'Conductor/performer refinement',
  'TPE4': 'Interpreted, remixed, or otherwise modified by',
  'TPOS': 'Part of a set',
  'TPUB': 'Publisher',
  'TRCK': 'Track number/Position in set',
  'TRDA': 'Recording dates',
  'TRSN': 'Internet radio station name',
  'TRSO': 'Internet radio station owner',
  'TSIZ': 'Size',
  'TSRC': 'ISRC (international standard recording code)',
  'TSSE': 'Software/Hardware and settings used for encoding',
  'TYER': 'Year',
  'TXXX': 'User defined text information frame',
  'UFID': 'Unique file identifier',
  'USER': 'Terms of use',
  'USLT': 'Unsychronized lyric/text transcription',
  'WCOM': 'Commercial information',
  'WCOP': 'Copyright/Legal information',
  'WOAF': 'Official audio file webpage',
  'WOAR': 'Official artist/performer webpage',
  'WOAS': 'Official audio source webpage',
  'WORS': 'Official internet radio station homepage',
  'WPAY': 'Payment',
  'WPUB': 'Publishers official webpage',
  'WXXX': 'User defined URL link frame',
};

// https://id3.org/id3v2.4.0-frames
const Map<String, String> frameV2p4Map = {
  'AENC': 'Audio encryption',
  'APIC': 'Attached picture',
  'ASPI': 'Audio seek point ',
  'COMM': 'Comments',
  'COMR': 'Commercial ',
  'ENCR': 'Encryption method registration',
  'EQU2': 'Equalisation (2)',
  'ETCO': 'Event timing ',
  'GEOB': 'General encapsulated object',
  'GRID': 'Group identification registr',
  'LINK': 'Linked inform',
  'MCDI': 'Music CD identifier',
  'MLLT': 'MPEG location lookup ',
  'OWNE': 'Ownership ',
  'PRIV': 'Private frame',
  'PCNT': 'Play counter',
  'POPM': 'Popularimeter',
  'POSS': 'Position synchronisation ',
  'RBUF': 'Recommended buffer size',
  'RVA2': 'Relative volume adjustment (2)',
  'RVRB': 'R',
  'SEEK': 'Seek frame',
  'SIGN': 'Signature frame',
  'SYLT': 'Synchronised lyric/text',
  'SYTC': 'Synchronised tempo ',
  'TALB': 'Album/Movie/Show title',
  'TBPM': 'BPM (beats per minute)',
  'TCOM': 'Composer',
  'TCON': 'Content type',
  'TCOP': 'Copyright message',
  'TDEN': 'Encoding time',
  'TDLY': 'Playlist delay',
  'TDOR': 'Original release time',
  'TDRC': 'Recording time',
  'TDRL': 'Release time',
  'TDTG': 'Tagging time',
  'TENC': 'Encoded by',
  'TEXT': 'Lyricist/Text writer',
  'TFLT': 'File type',
  'TIPL': 'Involved people list',
  'TIT1': 'Content group description',
  'TIT2': 'Title/songname/content description',
  'TIT3': 'Subtitle/Description refinement',
  'TKEY': 'Initial key',
  'TLAN': 'Language(s)',
  'TLEN': 'Length',
  'TMCL': 'Musician credits list',
  'TMED': 'Media type',
  'TMOO': 'Mood',
  'TOAL': 'Original album/movie/show title',
  'TOFN': 'Original filename',
  'TOLY': 'Original lyricist(s)/text writer(s)',
  'TOPE': 'Original artist(s)/performer(s)',
  'TOWN': 'File owner/licensee',
  'TPE1': 'Lead performer(s)/Soloist(s)',
  'TPE2': 'Band/orchestra/accompaniment',
  'TPE3': 'Conductor/performer refinement',
  'TPE4': 'Interpreted, remixed, or otherwise modified by',
  'TPOS': 'Part of a set',
  'TPRO': 'Produced notice',
  'TPUB': 'Publisher',
  'TRCK': 'Track number/Position in set',
  'TRSN': 'Internet radio station name',
  'TRSO': 'Internet radio station owner',
  'TSOA': 'Album sort order',
  'TSOP': 'Performer sort order',
  'TSOT': 'Title sort order',
  'TSRC': 'ISRC (international standard recording code)',
  'TSSE': 'Software/Hardware and settings used for encoding',
  'TSST': 'Set subtitle',
  'TXXX': 'User defined text information ',
  'UFID': 'Unique file identifier',
  'USER': 'Terms of use',
  'USLT': 'Unsynchronised lyric/text transcri',
  'WCOM': 'Commercial information',
  'WCOP': 'Copyright/Legal information',
  'WOAF': 'Official audio file webpage',
  'WOAR': 'Official artist/performer webpage',
  'WOAS': 'Official audio source webpage',
  'WORS': 'Official Internet radio station homepage',
  'WPAY': 'Payment',
  'WPUB': 'Publishers official webpage',
  'WXXX': 'User defined URL link frame',
};

const Map<int, String> kPictureType = {
  0x00: 'Other',
  0x01: "32x32 pixels 'file icon' (PNG only)",
  0x02: 'Other file icon',
  0x03: 'Cover (front)',
  0x04: 'Cover (back)',
  0x05: 'Leaflet page',
  0x06: 'Media (e.g. lable side of CD)',
  0x07: 'Lead artist/lead performer/soloist',
  0x08: 'Artist/performer',
  0x09: 'Conductor',
  0x0A: 'Band/Orchestra',
  0x0B: 'Composer',
  0x0C: 'Lyricist/text writer',
  0x0D: 'Recording Location',
  0x0E: 'During recording',
  0x0F: 'During performance',
  0x10: 'Movie/video screen capture',
  0x11: 'A bright coloured fish',
  0x12: 'Illustration',
  0x13: 'Band/artist logotype',
  0x14: 'Publisher/Studio logotype',
};
