import 'dart:core';

import 'package:collection/collection.dart';
import 'package:gc_wizard/tools/science_and_technology/colors/logic/colors_rgb.dart';

class XKCDColor {
  final String colorcode;
  final String name;

  const XKCDColor({
    required this.colorcode,
    required this.name,
  });
}

const Map<String, XKCDColor> XKCD_COLOR_CODES = {
  'cloudy blue': XKCDColor(colorcode: '#acc2d9', name: ''),
  'dark pastel green': XKCDColor(colorcode: '#56ae57', name: ''),
  'dust': XKCDColor(colorcode: '#b2996e', name: ''),
  'electric lime': XKCDColor(colorcode: '#a8ff04', name: ''),
  'fresh green': XKCDColor(colorcode: '#69d84f', name: ''),
  'light eggplant': XKCDColor(colorcode: '#894585', name: ''),
  'nasty green': XKCDColor(colorcode: '#70b23f', name: ''),
  'really light blue': XKCDColor(colorcode: '#d4ffff', name: ''),
  'tea': XKCDColor(colorcode: '#65ab7c', name: ''),
  'warm purple': XKCDColor(colorcode: '#952e8f', name: ''),
  'yellowish tan': XKCDColor(colorcode: '#fcfc81', name: ''),
  'cement': XKCDColor(colorcode: '#a5a391', name: ''),
  'dark grass green': XKCDColor(colorcode: '#388004', name: ''),
  'dusty teal': XKCDColor(colorcode: '#4c9085', name: ''),
  'grey teal': XKCDColor(colorcode: '#5e9b8a', name: ''),
  'macaroni and cheese': XKCDColor(colorcode: '#efb435', name: ''),
  'pinkish tan': XKCDColor(colorcode: '#d99b82', name: ''),
  'spruce': XKCDColor(colorcode: '#0a5f38', name: ''),
  'strong blue': XKCDColor(colorcode: '#0c06f7', name: ''),
  'toxic green': XKCDColor(colorcode: '#61de2a', name: ''),
  'windows blue': XKCDColor(colorcode: '#3778bf', name: ''),
  'blue blue': XKCDColor(colorcode: '#2242c7', name: ''),
  'blue with a hint of purple': XKCDColor(colorcode: '#533cc6', name: ''),
  'booger': XKCDColor(colorcode: '#9bb53c', name: 'booger'),
  'bright sea green': XKCDColor(colorcode: '#05ffa6', name: ''),
  'dark green blue': XKCDColor(colorcode: '#1f6357', name: ''),
  'deep turquoise': XKCDColor(colorcode: '#017374', name: ''),
  'green teal': XKCDColor(colorcode: '#0cb577', name: ''),
  'strong pink': XKCDColor(colorcode: '#ff0789', name: ''),
  'bland': XKCDColor(colorcode: '#afa88b', name: ''),
  'deep aqua': XKCDColor(colorcode: '#08787f', name: ''),
  'lavender pink': XKCDColor(colorcode: '#dd85d7', name: ''),
  'light moss green': XKCDColor(colorcode: '#a6c875', name: ''),
  'light seafoam green': XKCDColor(colorcode: '#a7ffb5', name: ''),
  'olive yellow':
      XKCDColor(colorcode: '#c2b709', name: 'ralcolorcodes_color_name_1020'),
  'pig pink': XKCDColor(colorcode: '#e78ea5', name: ''),
  'deep lilac': XKCDColor(colorcode: '#966ebd', name: ''),
  'desert': XKCDColor(colorcode: '#ccad60', name: ''),
  'dusty lavender': XKCDColor(colorcode: '#ac86a8', name: ''),
  'purpley grey': XKCDColor(colorcode: '#947e94', name: ''),
  'purply': XKCDColor(colorcode: '#983fb2', name: ''),
  'candy pink': XKCDColor(colorcode: '#ff63e9', name: ''),
  'light pastel green': XKCDColor(colorcode: '#b2fba5', name: ''),
  'boring green': XKCDColor(colorcode: '#63b365', name: ''),
  'kiwi green': XKCDColor(colorcode: '#8ee53f', name: ''),
  'light grey green': XKCDColor(colorcode: '#b7e1a1', name: ''),
  'orange pink': XKCDColor(colorcode: '#ff6f52', name: ''),
  'tea green': XKCDColor(colorcode: '#bdf8a3', name: ''),
  'very light brown': XKCDColor(colorcode: '#d3b683', name: ''),
  'egg shell': XKCDColor(colorcode: '#fffcc4', name: ''),
  'eggplant purple': XKCDColor(colorcode: '#430541', name: ''),
  'powder pink': XKCDColor(colorcode: '#ffb2d0', name: ''),
  'reddish grey': XKCDColor(colorcode: '#997570', name: ''),
  'baby shit brown': XKCDColor(colorcode: '#ad900d', name: ''),
  'liliac': XKCDColor(colorcode: '#c48efd', name: ''),
  'stormy blue': XKCDColor(colorcode: '#507b9c', name: ''),
  'ugly brown': XKCDColor(colorcode: '#7d7103', name: ''),
  'custard': XKCDColor(colorcode: '#fffd78', name: ''),
  'darkish pink': XKCDColor(colorcode: '#da467d', name: ''),
  'deep brown': XKCDColor(colorcode: '#410200', name: ''),
  'greenish beige': XKCDColor(colorcode: '#c9d179', name: ''),
  'manilla': XKCDColor(colorcode: '#fffa86', name: ''),
  'off blue': XKCDColor(colorcode: '#5684ae', name: ''),
  'battleship grey': XKCDColor(colorcode: '#6b7c85', name: ''),
  'browny green': XKCDColor(colorcode: '#6f6c0a', name: ''),
  'bruise': XKCDColor(colorcode: '#7e4071', name: ''),
  'kelley green': XKCDColor(colorcode: '#009337', name: ''),
  'sickly yellow': XKCDColor(colorcode: '#d0e429', name: ''),
  'sunny yellow': XKCDColor(colorcode: '#fff917', name: ''),
  'azul': XKCDColor(colorcode: '#1d5dec', name: ''),
  'darkgreen': XKCDColor(colorcode: '#054907', name: ''),
  'green slash yellow': XKCDColor(colorcode: '#b5ce08', name: ''),
  'lichen': XKCDColor(colorcode: '#8fb67b', name: ''),
  'light light green': XKCDColor(colorcode: '#c8ffb0', name: ''),
  'pale gold': XKCDColor(colorcode: '#fdde6c', name: ''),
  'sun yellow':
      XKCDColor(colorcode: '#ffdf22', name: 'ralcolorcodes_color_name_1037'),
  'tan green': XKCDColor(colorcode: '#a9be70', name: ''),
  'burple': XKCDColor(colorcode: '#6832e3', name: ''),
  'butterscotch': XKCDColor(colorcode: '#fdb147', name: ''),
  'toupe': XKCDColor(colorcode: '#c7ac7d', name: ''),
  'dark cream': XKCDColor(colorcode: '#fff39a', name: ''),
  'indian red': XKCDColor(colorcode: '#850e04', name: ''),
  'light lavendar': XKCDColor(colorcode: '#efc0fe', name: ''),
  'poison green': XKCDColor(colorcode: '#40fd14', name: ''),
  'baby puke green': XKCDColor(colorcode: '#b6c406', name: ''),
  'bright yellow green': XKCDColor(colorcode: '#9dff00', name: ''),
  'charcoal grey': XKCDColor(colorcode: '#3c4142', name: ''),
  'squash': XKCDColor(colorcode: '#f2ab15', name: ''),
  'cinnamon': XKCDColor(colorcode: '#ac4f06', name: ''),
  'light pea green': XKCDColor(colorcode: '#c4fe82', name: ''),
  'radioactive green': XKCDColor(colorcode: '#2cfa1f', name: ''),
  'raw sienna': XKCDColor(colorcode: '#9a6200', name: ''),
  'baby purple': XKCDColor(colorcode: '#ca9bf7', name: ''),
  'cocoa': XKCDColor(colorcode: '#875f42', name: ''),
  'light royal blue': XKCDColor(colorcode: '#3a2efe', name: ''),
  'orangeish': XKCDColor(colorcode: '#fd8d49', name: ''),
  'rust brown': XKCDColor(colorcode: '#8b3103', name: ''),
  'sand brown': XKCDColor(colorcode: '#cba560', name: ''),
  'swamp': XKCDColor(colorcode: '#698339', name: ''),
  'tealish green': XKCDColor(colorcode: '#0cdc73', name: ''),
  'burnt siena': XKCDColor(colorcode: '#b75203', name: ''),
  'camo': XKCDColor(colorcode: '#7f8f4e', name: ''),
  'dusk blue': XKCDColor(colorcode: '#26538d', name: ''),
  'fern': XKCDColor(colorcode: '#63a950', name: ''),
  'old rose': XKCDColor(colorcode: '#c87f89', name: ''),
  'pale light green': XKCDColor(colorcode: '#b1fc99', name: ''),
  'peachy pink': XKCDColor(colorcode: '#ff9a8a', name: ''),
  'rosy pink': XKCDColor(colorcode: '#f6688e', name: ''),
  'light bluish green': XKCDColor(colorcode: '#76fda8', name: ''),
  'light bright green': XKCDColor(colorcode: '#53fe5c', name: ''),
  'light neon green': XKCDColor(colorcode: '#4efd54', name: ''),
  'light seafoam': XKCDColor(colorcode: '#a0febf', name: ''),
  'tiffany blue': XKCDColor(colorcode: '#7bf2da', name: ''),
  'washed out green': XKCDColor(colorcode: '#bcf5a6', name: ''),
  'browny orange': XKCDColor(colorcode: '#ca6b02', name: ''),
  'nice blue': XKCDColor(colorcode: '#107ab0', name: ''),
  'sapphire': XKCDColor(colorcode: '#2138ab', name: ''),
  'greyish teal': XKCDColor(colorcode: '#719f91', name: ''),
  'orangey yellow': XKCDColor(colorcode: '#fdb915', name: 'ralcolorcodes_color_name_2000'),
  'parchment': XKCDColor(colorcode: '#fefcaf', name: ''),
  'straw': XKCDColor(colorcode: '#fcf679', name: ''),
  'very dark brown': XKCDColor(colorcode: '#1d0200', name: ''),
  'terracota': XKCDColor(colorcode: '#cb6843', name: ''),
  'ugly blue': XKCDColor(colorcode: '#31668a', name: ''),
  'clear blue': XKCDColor(colorcode: '#247afd', name: ''),
  'creme': XKCDColor(colorcode: '#ffffb6', name: ''),
  'foam green': XKCDColor(colorcode: '#90fda9', name: ''),
  'grey slash green': XKCDColor(colorcode: '#86a17d', name: ''),
  'light gold': XKCDColor(colorcode: '#fddc5c', name: ''),
  'seafoam blue': XKCDColor(colorcode: '#78d1b6', name: ''),
  'topaz': XKCDColor(colorcode: '#13bbaf', name: ''),
  'violet pink': XKCDColor(colorcode: '#fb5ffc', name: ''),
  'wintergreen': XKCDColor(colorcode: '#20f986', name: ''),
  'yellow tan': XKCDColor(colorcode: '#ffe36e', name: ''),
  'dark fuchsia': XKCDColor(colorcode: '#9d0759', name: ''),
  'indigo blue': XKCDColor(colorcode: '#3a18b1', name: ''),
  'light yellowish green': XKCDColor(colorcode: '#c2ff89', name: ''),
  'pale magenta': XKCDColor(colorcode: '#d767ad', name: ''),
  'rich purple': XKCDColor(colorcode: '#720058', name: ''),
  'sunflower yellow': XKCDColor(colorcode: '#ffda03', name: ''),
  'green slash blue': XKCDColor(colorcode: '#01c08d', name: ''),
  'leather': XKCDColor(colorcode: '#ac7434', name: ''),
  'racing green': XKCDColor(colorcode: '#014600', name: ''),
  'vivid purple': XKCDColor(colorcode: '#9900fa', name: ''),
  'dark royal blue': XKCDColor(colorcode: '#02066f', name: ''),
  'hazel': XKCDColor(colorcode: '#8e7618', name: ''),
  'muted pink': XKCDColor(colorcode: '#d1768f', name: ''),
  'booger green': XKCDColor(colorcode: '#96b403', name: ''),
  'canary': XKCDColor(colorcode: '#fdff63', name: ''),
  'cool grey': XKCDColor(colorcode: '#95a3a6', name: ''),
  'dark taupe': XKCDColor(colorcode: '#7f684e', name: ''),
  'darkish purple': XKCDColor(colorcode: '#751973', name: ''),
  'true green': XKCDColor(colorcode: '#089404', name: ''),
  'coral pink': XKCDColor(colorcode: '#ff6163', name: ''),
  'dark sage': XKCDColor(colorcode: '#598556', name: ''),
  'dark slate blue': XKCDColor(colorcode: '#214761', name: ''),
  'flat blue': XKCDColor(colorcode: '#3c73a8', name: ''),
  'mushroom': XKCDColor(colorcode: '#ba9e88', name: ''),
  'rich blue': XKCDColor(colorcode: '#021bf9', name: ''),
  'dirty purple': XKCDColor(colorcode: '#734a65', name: ''),
  'greenblue': XKCDColor(colorcode: '#23c48b', name: ''),
  'icky green': XKCDColor(colorcode: '#8fae22', name: ''),
  'light khaki': XKCDColor(colorcode: '#e6f2a2', name: ''),
  'warm blue': XKCDColor(colorcode: '#4b57db', name: ''),
  'dark hot pink': XKCDColor(colorcode: '#d90166', name: ''),
  'deep sea blue': XKCDColor(colorcode: '#015482', name: ''),
  'carmine': XKCDColor(colorcode: '#9d0216', name: ''),
  'dark yellow green': XKCDColor(colorcode: '#728f02', name: ''),
  'pale peach': XKCDColor(colorcode: '#ffe5ad', name: ''),
  'plum purple': XKCDColor(colorcode: '#4e0550', name: ''),
  'golden rod': XKCDColor(colorcode: '#f9bc08', name: ''),
  'neon red': XKCDColor(colorcode: '#ff073a', name: ''),
  'old pink': XKCDColor(colorcode: '#c77986', name: ''),
  'very pale blue': XKCDColor(colorcode: '#d6fffe', name: ''),
  'blood orange': XKCDColor(colorcode: '#fe4b03', name: ''),
  'grapefruit': XKCDColor(colorcode: '#fd5956', name: ''),
  'sand yellow':
      XKCDColor(colorcode: '#fce166', name: 'ralcolorcodes_color_name_1002'),
  'clay brown': XKCDColor(colorcode: '#b2713d', name: 'ralcolorcodes_color_name_8003'),
  'dark blue grey': XKCDColor(colorcode: '#1f3b4d', name: ''),
  'flat green': XKCDColor(colorcode: '#699d4c', name: ''),
  'light green blue': XKCDColor(colorcode: '#56fca2', name: ''),
  'warm pink': XKCDColor(colorcode: '#fb5581', name: ''),
  'dodger blue': XKCDColor(colorcode: '#3e82fc', name: ''),
  'gross green': XKCDColor(colorcode: '#a0bf16', name: ''),
  'ice': XKCDColor(colorcode: '#d6fffa', name: ''),
  'metallic blue': XKCDColor(colorcode: '#4f738e', name: ''),
  'pale salmon': XKCDColor(colorcode: '#ffb19a', name: ''),
  'sap green': XKCDColor(colorcode: '#5c8b15', name: ''),
  'algae': XKCDColor(colorcode: '#54ac68', name: ''),
  'bluey grey': XKCDColor(colorcode: '#89a0b0', name: ''),
  'greeny grey': XKCDColor(colorcode: '#7ea07a', name: ''),
  'highlighter green': XKCDColor(colorcode: '#1bfc06', name: ''),
  'light light blue': XKCDColor(colorcode: '#cafffb', name: ''),
  'light mint': XKCDColor(colorcode: '#b6ffbb', name: ''),
  'raw umber': XKCDColor(colorcode: '#a75e09', name: ''),
  'vivid blue': XKCDColor(colorcode: '#152eff', name: ''),
  'deep lavender': XKCDColor(colorcode: '#8d5eb7', name: ''),
  'dull teal': XKCDColor(colorcode: '#5f9e8f', name: ''),
  'light greenish blue': XKCDColor(colorcode: '#63f7b4', name: ''),
  'mud green': XKCDColor(colorcode: '#606602', name: ''),
  'pinky': XKCDColor(colorcode: '#fc86aa', name: ''),
  'red wine':
      XKCDColor(colorcode: '#8c0034', name: 'ralcolorcodes_color_name_3005'),
  'shit green': XKCDColor(colorcode: '#758000', name: ''),
  'tan brown': XKCDColor(colorcode: '#ab7e4c', name: ''),
  'darkblue': XKCDColor(colorcode: '#030764', name: ''),
  'rosa': XKCDColor(colorcode: '#fe86a4', name: ''),
  'lipstick': XKCDColor(colorcode: '#d5174e', name: ''),
  'pale mauve': XKCDColor(colorcode: '#fed0fc', name: ''),
  'claret': XKCDColor(colorcode: '#680018', name: ''),
  'dandelion': XKCDColor(colorcode: '#fedf08', name: ''),
  'orangered': XKCDColor(colorcode: '#fe420f', name: ''),
  'poop green': XKCDColor(colorcode: '#6f7c00', name: ''),
  'ruby': XKCDColor(colorcode: '#ca0147', name: ''),
  'dark': XKCDColor(colorcode: '#1b2431', name: ''),
  'greenish turquoise': XKCDColor(colorcode: '#00fbb0', name: ''),
  'pastel red': XKCDColor(colorcode: '#db5856', name: ''),
  'piss yellow': XKCDColor(colorcode: '#ddd618', name: ''),
  'bright cyan': XKCDColor(colorcode: '#41fdfe', name: ''),
  'dark coral': XKCDColor(colorcode: '#cf524e', name: ''),
  'algae green': XKCDColor(colorcode: '#21c36f', name: ''),
  'darkish red': XKCDColor(colorcode: '#a90308', name: ''),
  'reddy brown': XKCDColor(colorcode: '#6e1005', name: ''),
  'blush pink': XKCDColor(colorcode: '#fe828c', name: ''),
  'camouflage green': XKCDColor(colorcode: '#4b6113', name: ''),
  'lawn green': XKCDColor(colorcode: '#4da409', name: ''),
  'putty': XKCDColor(colorcode: '#beae8a', name: ''),
  'vibrant blue': XKCDColor(colorcode: '#0339f8', name: ''),
  'dark sand': XKCDColor(colorcode: '#a88f59', name: ''),
  'purple slash blue': XKCDColor(colorcode: '#5d21d0', name: ''),
  'saffron': XKCDColor(colorcode: '#feb209', name: ''),
  'twilight': XKCDColor(colorcode: '#4e518b', name: ''),
  'warm brown': XKCDColor(colorcode: '#964e02', name: ''),
  'bluegrey': XKCDColor(colorcode: '#85a3b2', name: ''),
  'bubble gum pink': XKCDColor(colorcode: '#ff69af', name: ''),
  'duck egg blue': XKCDColor(colorcode: '#c3fbf4', name: ''),
  'greenish cyan': XKCDColor(colorcode: '#2afeb7', name: ''),
  'petrol': XKCDColor(colorcode: '#005f6a', name: ''),
  'royal': XKCDColor(colorcode: '#0c1793', name: ''),
  'butter': XKCDColor(colorcode: '#ffff81', name: ''),
  'dusty orange': XKCDColor(colorcode: '#f0833a', name: ''),
  'off yellow': XKCDColor(colorcode: '#f1f33f', name: ''),
  'pale olive green': XKCDColor(colorcode: '#b1d27b', name: ''),
  'orangish': XKCDColor(colorcode: '#fc824a', name: ''),
  'leaf': XKCDColor(colorcode: '#71aa34', name: ''),
  'light blue grey': XKCDColor(colorcode: '#b7c9e2', name: ''),
  'dried blood': XKCDColor(colorcode: '#4b0101', name: ''),
  'lightish purple': XKCDColor(colorcode: '#a552e6', name: ''),
  'rusty red': XKCDColor(colorcode: '#af2f0d', name: ''),
  'lavender blue': XKCDColor(colorcode: '#8b88f8', name: ''),
  'light grass green': XKCDColor(colorcode: '#9af764', name: ''),
  'light mint green': XKCDColor(colorcode: '#a6fbb2', name: ''),
  'sunflower': XKCDColor(colorcode: '#ffc512', name: ''),
  'velvet': XKCDColor(colorcode: '#750851', name: ''),
  'brick orange': XKCDColor(colorcode: '#c14a09', name: ''),
  'lightish red': XKCDColor(colorcode: '#fe2f4a', name: ''),
  'pure blue': XKCDColor(colorcode: '#0203e2', name: ''),
  'twilight blue': XKCDColor(colorcode: '#0a437a', name: ''),
  'violet red': XKCDColor(colorcode: '#a50055', name: ''),
  'yellowy brown': XKCDColor(colorcode: '#ae8b0c', name: ''),
  'carnation': XKCDColor(colorcode: '#fd798f', name: ''),
  'muddy yellow': XKCDColor(colorcode: '#bfac05', name: ''),
  'dark seafoam green': XKCDColor(colorcode: '#3eaf76', name: ''),
  'deep rose': XKCDColor(colorcode: '#c74767', name: ''),
  'dusty red': XKCDColor(colorcode: '#b9484e', name: ''),
  'grey slash blue': XKCDColor(colorcode: '#647d8e', name: ''),
  'lemon lime': XKCDColor(colorcode: '#bffe28', name: ''),
  'purple slash pink': XKCDColor(colorcode: '#d725de', name: ''),
  'brown yellow': XKCDColor(colorcode: '#b29705', name: ''),
  'purple brown': XKCDColor(colorcode: '#673a3f', name: ''),
  'wisteria': XKCDColor(colorcode: '#a87dc2', name: ''),
  'banana yellow': XKCDColor(colorcode: '#fafe4b', name: ''),
  'lipstick red': XKCDColor(colorcode: '#c0022f', name: ''),
  'water blue': XKCDColor(colorcode: '#0e87cc', name: 'ralcolorcodes_color_name_5021'),
  'brown grey': XKCDColor(colorcode: '#8d8468', name: 'ralcolorcodes_color_name_7013'),
  'vibrant purple': XKCDColor(colorcode: '#ad03de', name: ''),
  'baby green': XKCDColor(colorcode: '#8cff9e', name: ''),
  'barf green': XKCDColor(colorcode: '#94ac02', name: ''),
  'eggshell blue': XKCDColor(colorcode: '#c4fff7', name: ''),
  'sandy yellow': XKCDColor(colorcode: '#fdee73', name: ''),
  'cool green': XKCDColor(colorcode: '#33b864', name: ''),
  'pale': XKCDColor(colorcode: '#fff9d0', name: ''),
  'blue slash grey': XKCDColor(colorcode: '#758da3', name: ''),
  'hot magenta': XKCDColor(colorcode: '#f504c9', name: ''),
  'greyblue': XKCDColor(colorcode: '#77a1b5', name: ''),
  'purpley': XKCDColor(colorcode: '#8756e4', name: ''),
  'baby shit green': XKCDColor(colorcode: '#889717', name: ''),
  'brownish pink': XKCDColor(colorcode: '#c27e79', name: ''),
  'dark aquamarine': XKCDColor(colorcode: '#017371', name: ''),
  'diarrhea': XKCDColor(colorcode: '#9f8303', name: ''),
  'light mustard': XKCDColor(colorcode: '#f7d560', name: ''),
  'pale sky blue': XKCDColor(colorcode: '#bdf6fe', name: ''),
  'turtle green': XKCDColor(colorcode: '#75b84f', name: ''),
  'bright olive': XKCDColor(colorcode: '#9cbb04', name: ''),
  'dark grey blue': XKCDColor(colorcode: '#29465b', name: ''),
  'greeny brown': XKCDColor(colorcode: '#696006', name: ''),
  'lemon green': XKCDColor(colorcode: '#adf802', name: ''),
  'light periwinkle': XKCDColor(colorcode: '#c1c6fc', name: ''),
  'seaweed green': XKCDColor(colorcode: '#35ad6b', name: ''),
  'sunshine yellow': XKCDColor(colorcode: '#fffd37', name: ''),
  'ugly purple': XKCDColor(colorcode: '#a442a0', name: ''),
  'medium pink': XKCDColor(colorcode: '#f36196', name: ''),
  'puke brown': XKCDColor(colorcode: '#947706', name: ''),
  'very light pink': XKCDColor(colorcode: '#fff4f2', name: ''),
  'viridian': XKCDColor(colorcode: '#1e9167', name: ''),
  'bile': XKCDColor(colorcode: '#b5c306', name: ''),
  'faded yellow': XKCDColor(colorcode: '#feff7f', name: ''),
  'very pale green': XKCDColor(colorcode: '#cffdbc', name: ''),
  'vibrant green': XKCDColor(colorcode: '#0add08', name: ''),
  'bright lime': XKCDColor(colorcode: '#87fd05', name: ''),
  'spearmint': XKCDColor(colorcode: '#1ef876', name: ''),
  'light aquamarine': XKCDColor(colorcode: '#7bfdc7', name: ''),
  'light sage': XKCDColor(colorcode: '#bcecac', name: ''),
  'yellowgreen': XKCDColor(colorcode: '#bbf90f', name: ''),
  'baby poo': XKCDColor(colorcode: '#ab9004', name: ''),
  'dark seafoam': XKCDColor(colorcode: '#1fb57a', name: ''),
  'deep teal': XKCDColor(colorcode: '#00555a', name: ''),
  'heather': XKCDColor(colorcode: '#a484ac', name: ''),
  'rust orange': XKCDColor(colorcode: '#c45508', name: ''),
  'dirty blue': XKCDColor(colorcode: '#3f829d', name: ''),
  'fern green': XKCDColor(colorcode: '#548d44', name: 'ralcolorcodes_color_name_6025'),
  'bright lilac': XKCDColor(colorcode: '#c95efb', name: ''),
  'weird green': XKCDColor(colorcode: '#3ae57f', name: ''),
  'peacock blue': XKCDColor(colorcode: '#016795', name: ''),
  'avocado green': XKCDColor(colorcode: '#87a922', name: ''),
  'faded orange': XKCDColor(colorcode: '#f0944d', name: ''),
  'grape purple': XKCDColor(colorcode: '#5d1451', name: ''),
  'hot green': XKCDColor(colorcode: '#25ff29', name: ''),
  'lime yellow': XKCDColor(colorcode: '#d0fe1d', name: ''),
  'mango': XKCDColor(colorcode: '#ffa62b', name: ''),
  'shamrock': XKCDColor(colorcode: '#01b44c', name: ''),
  'bubblegum': XKCDColor(colorcode: '#ff6cb5', name: ''),
  'purplish brown': XKCDColor(colorcode: '#6b4247', name: ''),
  'vomit yellow': XKCDColor(colorcode: '#c7c10c', name: ''),
  'pale cyan': XKCDColor(colorcode: '#b7fffa', name: ''),
  'key lime': XKCDColor(colorcode: '#aeff6e', name: ''),
  'tomato red': XKCDColor(colorcode: '#ec2d01', name: 'ralcolorcodes_color_name_3013'),
  'lightgreen': XKCDColor(colorcode: '#76ff7b', name: ''),
  'merlot': XKCDColor(colorcode: '#730039', name: ''),
  'night blue': XKCDColor(colorcode: '#040348', name: 'ralcolorcodes_color_name_5022'),
  'purpleish pink': XKCDColor(colorcode: '#df4ec8', name: ''),
  'apple': XKCDColor(colorcode: '#6ecb3c', name: ''),
  'baby poop green': XKCDColor(colorcode: '#8f9805', name: ''),
  'green apple': XKCDColor(colorcode: '#5edc1f', name: ''),
  'heliotrope': XKCDColor(colorcode: '#d94ff5', name: ''),
  'yellow slash green': XKCDColor(colorcode: '#c8fd3d', name: ''),
  'almost black': XKCDColor(colorcode: '#070d0d', name: ''),
  'cool blue': XKCDColor(colorcode: '#4984b8', name: ''),
  'leafy green': XKCDColor(colorcode: '#51b73b', name: ''),
  'mustard brown': XKCDColor(colorcode: '#ac7e04', name: ''),
  'dusk': XKCDColor(colorcode: '#4e5481', name: ''),
  'dull brown': XKCDColor(colorcode: '#876e4b', name: ''),
  'frog green': XKCDColor(colorcode: '#58bc08', name: ''),
  'vivid green': XKCDColor(colorcode: '#2fef10', name: ''),
  'bright light green': XKCDColor(colorcode: '#2dfe54', name: ''),
  'fluro green': XKCDColor(colorcode: '#0aff02', name: ''),
  'kiwi': XKCDColor(colorcode: '#9cef43', name: ''),
  'seaweed': XKCDColor(colorcode: '#18d17b', name: ''),
  'navy green': XKCDColor(colorcode: '#35530a', name: ''),
  'ultramarine blue': XKCDColor(colorcode: '#1805db', name: 'ralcolorcodes_color_name_5002'),
  'iris': XKCDColor(colorcode: '#6258c4', name: ''),
  'pastel orange':
      XKCDColor(colorcode: '#ff964f', name: 'ralcolorcodes_color_name_2003'),
  'yellowish orange': XKCDColor(colorcode: '#ffab0f', name: ''),
  'perrywinkle': XKCDColor(colorcode: '#8f8ce7', name: ''),
  'tealish': XKCDColor(colorcode: '#24bca8', name: ''),
  'dark plum': XKCDColor(colorcode: '#3f012c', name: ''),
  'pear': XKCDColor(colorcode: '#cbf85f', name: ''),
  'pinkish orange': XKCDColor(colorcode: '#ff724c', name: ''),
  'midnight purple': XKCDColor(colorcode: '#280137', name: ''),
  'light urple': XKCDColor(colorcode: '#b36ff6', name: ''),
  'dark mint': XKCDColor(colorcode: '#48c072', name: ''),
  'greenish tan': XKCDColor(colorcode: '#bccb7a', name: ''),
  'light burgundy': XKCDColor(colorcode: '#a8415b', name: ''),
  'turquoise blue': XKCDColor(colorcode: '#06b1c4', name: 'ralcolorcodes_color_name_5018'),
  'ugly pink': XKCDColor(colorcode: '#cd7584', name: ''),
  'sandy': XKCDColor(colorcode: '#f1da7a', name: ''),
  'electric pink': XKCDColor(colorcode: '#ff0490', name: ''),
  'muted purple': XKCDColor(colorcode: '#805b87', name: ''),
  'mid green': XKCDColor(colorcode: '#50a747', name: ''),
  'greyish': XKCDColor(colorcode: '#a8a495', name: ''),
  'neon yellow': XKCDColor(colorcode: '#cfff04', name: ''),
  'banana': XKCDColor(colorcode: '#ffff7e', name: ''),
  'carnation pink': XKCDColor(colorcode: '#ff7fa7', name: ''),
  'tomato': XKCDColor(colorcode: '#ef4026', name: ''),
  'sea': XKCDColor(colorcode: '#3c9992', name: ''),
  'muddy brown': XKCDColor(colorcode: '#886806', name: ''),
  'turquoise green': XKCDColor(colorcode: '#04f489', name: 'ralcolorcodes_color_name_6016'),
  'buff': XKCDColor(colorcode: '#fef69e', name: ''),
  'fawn': XKCDColor(colorcode: '#cfaf7b', name: ''),
  'muted blue': XKCDColor(colorcode: '#3b719f', name: ''),
  'pale rose': XKCDColor(colorcode: '#fdc1c5', name: ''),
  'dark mint green': XKCDColor(colorcode: '#20c073', name: ''),
  'amethyst': XKCDColor(colorcode: '#9b5fc0', name: ''),
  'blue slash green': XKCDColor(colorcode: '#0f9b8e', name: ''),
  'chestnut': XKCDColor(colorcode: '#742802', name: ''),
  'sick green': XKCDColor(colorcode: '#9db92c', name: ''),
  'pea': XKCDColor(colorcode: '#a4bf20', name: ''),
  'rusty orange': XKCDColor(colorcode: '#cd5909', name: ''),
  'stone': XKCDColor(colorcode: '#ada587', name: ''),
  'rose red': XKCDColor(colorcode: '#be013c', name: ''),
  'pale aqua': XKCDColor(colorcode: '#b8ffeb', name: ''),
  'deep orange':
      XKCDColor(colorcode: '#dc4d01', name: 'ralcolorcodes_color_name_2011'),
  'earth': XKCDColor(colorcode: '#a2653e', name: ''),
  'mossy green': XKCDColor(colorcode: '#638b27', name: ''),
  'grassy green': XKCDColor(colorcode: '#419c03', name: ''),
  'pale lime green': XKCDColor(colorcode: '#b1ff65', name: ''),
  'light grey blue': XKCDColor(colorcode: '#9dbcd4', name: ''),
  'pale grey': XKCDColor(colorcode: '#fdfdfe', name: ''),
  'asparagus': XKCDColor(colorcode: '#77ab56', name: ''),
  'blueberry': XKCDColor(colorcode: '#464196', name: ''),
  'purple red':
      XKCDColor(colorcode: '#990147', name: 'ralcolorcodes_color_name_3004'),
  'pale lime': XKCDColor(colorcode: '#befd73', name: ''),
  'greenish teal': XKCDColor(colorcode: '#32bf84', name: ''),
  'caramel': XKCDColor(colorcode: '#af6f09', name: ''),
  'deep magenta': XKCDColor(colorcode: '#a0025c', name: ''),
  'light peach': XKCDColor(colorcode: '#ffd8b1', name: ''),
  'milk chocolate': XKCDColor(colorcode: '#7f4e1e', name: ''),
  'ocher': XKCDColor(colorcode: '#bf9b0c', name: ''),
  'off green': XKCDColor(colorcode: '#6ba353', name: ''),
  'purply pink': XKCDColor(colorcode: '#f075e6', name: ''),
  'lightblue': XKCDColor(colorcode: '#7bc8f6', name: ''),
  'dusky blue': XKCDColor(colorcode: '#475f94', name: ''),
  'golden': XKCDColor(colorcode: '#f5bf03', name: ''),
  'light beige': XKCDColor(colorcode: '#fffeb6', name: ''),
  'butter yellow': XKCDColor(colorcode: '#fffd74', name: ''),
  'dusky purple': XKCDColor(colorcode: '#895b7b', name: ''),
  'french blue': XKCDColor(colorcode: '#436bad', name: ''),
  'ugly yellow': XKCDColor(colorcode: '#d0c101', name: ''),
  'greeny yellow': XKCDColor(colorcode: '#c6f808', name: ''),
  'orangish red': XKCDColor(colorcode: '#f43605', name: ''),
  'shamrock green': XKCDColor(colorcode: '#02c14d', name: ''),
  'orangish brown': XKCDColor(colorcode: '#b25f03', name: ''),
  'tree green': XKCDColor(colorcode: '#2a7e19', name: ''),
  'deep violet': XKCDColor(colorcode: '#490648', name: ''),
  'gunmetal': XKCDColor(colorcode: '#536267', name: ''),
  'blue slash purple': XKCDColor(colorcode: '#5a06ef', name: ''),
  'cherry': XKCDColor(colorcode: '#cf0234', name: ''),
  'sandy brown': XKCDColor(colorcode: '#c4a661', name: ''),
  'warm grey': XKCDColor(colorcode: '#978a84', name: ''),
  'dark indigo': XKCDColor(colorcode: '#1f0954', name: ''),
  'midnight': XKCDColor(colorcode: '#03012d', name: ''),
  'bluey green': XKCDColor(colorcode: '#2bb179', name: ''),
  'grey pink': XKCDColor(colorcode: '#c3909b', name: ''),
  'soft purple': XKCDColor(colorcode: '#a66fb5', name: ''),
  'blood': XKCDColor(colorcode: '#770001', name: ''),
  'brown red':
      XKCDColor(colorcode: '#922b05', name: 'ralcolorcodes_color_name_3011'),
  'medium grey': XKCDColor(colorcode: '#7d7f7c', name: ''),
  'berry': XKCDColor(colorcode: '#990f4b', name: ''),
  'poo': XKCDColor(colorcode: '#8f7303', name: ''),
  'purpley pink': XKCDColor(colorcode: '#c83cb9', name: ''),
  'light salmon': XKCDColor(colorcode: '#fea993', name: ''),
  'snot': XKCDColor(colorcode: '#acbb0d', name: ''),
  'easter purple': XKCDColor(colorcode: '#c071fe', name: ''),
  'light yellow green': XKCDColor(colorcode: '#ccfd7f', name: ''),
  'dark navy blue': XKCDColor(colorcode: '#00022e', name: ''),
  'drab': XKCDColor(colorcode: '#828344', name: ''),
  'light rose': XKCDColor(colorcode: '#ffc5cb', name: ''),
  'rouge': XKCDColor(colorcode: '#ab1239', name: ''),
  'purplish red': XKCDColor(colorcode: '#b0054b', name: ''),
  'slime green': XKCDColor(colorcode: '#99cc04', name: ''),
  'baby poop': XKCDColor(colorcode: '#937c00', name: ''),
  'irish green': XKCDColor(colorcode: '#019529', name: ''),
  'pink slash purple': XKCDColor(colorcode: '#ef1de7', name: ''),
  'dark navy': XKCDColor(colorcode: '#000435', name: ''),
  'greeny blue': XKCDColor(colorcode: '#42b395', name: ''),
  'light plum': XKCDColor(colorcode: '#9d5783', name: ''),
  'pinkish grey': XKCDColor(colorcode: '#c8aca9', name: ''),
  'dirty orange': XKCDColor(colorcode: '#c87606', name: ''),
  'rust red': XKCDColor(colorcode: '#aa2704', name: ''),
  'pale lilac': XKCDColor(colorcode: '#e4cbff', name: ''),
  'orangey red': XKCDColor(colorcode: '#fa4224', name: ''),
  'primary blue': XKCDColor(colorcode: '#0804f9', name: ''),
  'kermit green': XKCDColor(colorcode: '#5cb200', name: ''),
  'brownish purple': XKCDColor(colorcode: '#76424e', name: ''),
  'murky green': XKCDColor(colorcode: '#6c7a0e', name: ''),
  'wheat': XKCDColor(colorcode: '#fbdd7e', name: ''),
  'very dark purple': XKCDColor(colorcode: '#2a0134', name: ''),
  'bottle green': XKCDColor(colorcode: '#044a05', name: 'ralcolorcodes_color_name_6007'),
  'watermelon': XKCDColor(colorcode: '#fd4659', name: ''),
  'deep sky blue': XKCDColor(colorcode: '#0d75f8', name: ''),
  'fire engine red': XKCDColor(colorcode: '#fe0002', name: ''),
  'yellow ochre':
      XKCDColor(colorcode: '#cb9d06', name: 'ralcolorcodes_color_name_1024'),
  'pumpkin orange':
      XKCDColor(colorcode: '#fb7d07', name: 'ralcolorcodes_color_name_2000'),
  'pale olive': XKCDColor(colorcode: '#b9cc81', name: ''),
  'light lilac': XKCDColor(colorcode: '#edc8ff', name: ''),
  'lightish green': XKCDColor(colorcode: '#61e160', name: ''),
  'carolina blue': XKCDColor(colorcode: '#8ab8fe', name: ''),
  'mulberry': XKCDColor(colorcode: '#920a4e', name: ''),
  'shocking pink': XKCDColor(colorcode: '#fe02a2', name: ''),
  'auburn': XKCDColor(colorcode: '#9a3001', name: ''),
  'bright lime green': XKCDColor(colorcode: '#65fe08', name: ''),
  'celadon': XKCDColor(colorcode: '#befdb7', name: ''),
  'pinkish brown': XKCDColor(colorcode: '#b17261', name: ''),
  'poo brown': XKCDColor(colorcode: '#885f01', name: ''),
  'bright sky blue': XKCDColor(colorcode: '#02ccfe', name: ''),
  'celery': XKCDColor(colorcode: '#c1fd95', name: ''),
  'dirt brown': XKCDColor(colorcode: '#836539', name: ''),
  'strawberry': XKCDColor(colorcode: '#fb2943', name: ''),
  'dark lime': XKCDColor(colorcode: '#84b701', name: ''),
  'copper': XKCDColor(colorcode: '#b66325', name: ''),
  'medium brown': XKCDColor(colorcode: '#7f5112', name: ''),
  'muted green': XKCDColor(colorcode: '#5fa052', name: ''),
  'robins egg': XKCDColor(colorcode: '#6dedfd', name: ''),
  'bright aqua': XKCDColor(colorcode: '#0bf9ea', name: ''),
  'bright lavender': XKCDColor(colorcode: '#c760ff', name: ''),
  'ivory':
      XKCDColor(colorcode: '#ffffcb', name: 'ralcolorcodes_color_name_1014'),
  'very light purple': XKCDColor(colorcode: '#f6cefc', name: ''),
  'light navy': XKCDColor(colorcode: '#155084', name: ''),
  'pink red': XKCDColor(colorcode: '#f5054f', name: ''),
  'olive brown': XKCDColor(colorcode: '#645403', name: 'ralcolorcodes_color_name_8008'),
  'poop brown': XKCDColor(colorcode: '#7a5901', name: ''),
  'mustard green': XKCDColor(colorcode: '#a8b504', name: ''),
  'ocean green': XKCDColor(colorcode: '#3d9973', name: ''),
  'very dark blue': XKCDColor(colorcode: '#000133', name: ''),
  'dusty green': XKCDColor(colorcode: '#76a973', name: ''),
  'light navy blue': XKCDColor(colorcode: '#2e5a88', name: ''),
  'minty green': XKCDColor(colorcode: '#0bf77d', name: ''),
  'adobe': XKCDColor(colorcode: '#bd6c48', name: ''),
  'barney': XKCDColor(colorcode: '#ac1db8', name: ''),
  'jade green': XKCDColor(colorcode: '#2baf6a', name: ''),
  'bright light blue': XKCDColor(colorcode: '#26f7fd', name: ''),
  'light lime': XKCDColor(colorcode: '#aefd6c', name: ''),
  'dark khaki': XKCDColor(colorcode: '#9b8f55', name: ''),
  'orange yellow': XKCDColor(colorcode: '#ffad01', name: ''),
  'ocre': XKCDColor(colorcode: '#c69c04', name: ''),
  'maize': XKCDColor(colorcode: '#f4d054', name: ''),
  'faded pink': XKCDColor(colorcode: '#de9dac', name: ''),
  'british racing green': XKCDColor(colorcode: '#05480d', name: ''),
  'sandstone': XKCDColor(colorcode: '#c9ae74', name: ''),
  'mud brown': XKCDColor(colorcode: '#60460f', name: ''),
  'light sea green': XKCDColor(colorcode: '#98f6b0', name: ''),
  'robin egg blue': XKCDColor(colorcode: '#8af1fe', name: ''),
  'aqua marine': XKCDColor(colorcode: '#2ee8bb', name: ''),
  'dark sea green': XKCDColor(colorcode: '#11875d', name: ''),
  'soft pink': XKCDColor(colorcode: '#fdb0c0', name: ''),
  'orangey brown': XKCDColor(colorcode: '#b16002', name: ''),
  'cherry red': XKCDColor(colorcode: '#f7022a', name: ''),
  'burnt yellow': XKCDColor(colorcode: '#d5ab09', name: ''),
  'brownish grey': XKCDColor(colorcode: '#86775f', name: ''),
  'camel': XKCDColor(colorcode: '#c69f59', name: 'camel'),
  'purplish grey': XKCDColor(colorcode: '#7a687f', name: ''),
  'marine': XKCDColor(colorcode: '#042e60', name: ''),
  'greyish pink': XKCDColor(colorcode: '#c88d94', name: ''),
  'pale turquoise': XKCDColor(colorcode: '#a5fbd5', name: ''),
  'pastel yellow':
      XKCDColor(colorcode: '#fffe71', name: 'ralcolorcodes_color_name_1034'),
  'bluey purple': XKCDColor(colorcode: '#6241c7', name: ''),
  'canary yellow': XKCDColor(colorcode: '#fffe40', name: ''),
  'faded red': XKCDColor(colorcode: '#d3494e', name: ''),
  'sepia': XKCDColor(colorcode: '#985e2b', name: ''),
  'coffee': XKCDColor(colorcode: '#a6814c', name: ''),
  'bright magenta': XKCDColor(colorcode: '#ff08e8', name: ''),
  'mocha': XKCDColor(colorcode: '#9d7651', name: ''),
  'ecru': XKCDColor(colorcode: '#feffca', name: ''),
  'purpleish': XKCDColor(colorcode: '#98568d', name: ''),
  'cranberry': XKCDColor(colorcode: '#9e003a', name: ''),
  'darkish green': XKCDColor(colorcode: '#287c37', name: ''),
  'brown orange': XKCDColor(colorcode: '#b96902', name: ''),
  'dusky rose': XKCDColor(colorcode: '#ba6873', name: ''),
  'melon': XKCDColor(colorcode: '#ff7855', name: ''),
  'sickly green': XKCDColor(colorcode: '#94b21c', name: ''),
  'silver': XKCDColor(colorcode: '#c5c9c7', name: 'common_color_silver'),
  'purply blue': XKCDColor(colorcode: '#661aee', name: ''),
  'purpleish blue': XKCDColor(colorcode: '#6140ef', name: ''),
  'hospital green': XKCDColor(colorcode: '#9be5aa', name: ''),
  'shit brown': XKCDColor(colorcode: '#7b5804', name: ''),
  'mid blue': XKCDColor(colorcode: '#276ab3', name: ''),
  'amber': XKCDColor(colorcode: '#feb308', name: 'amber'),
  'easter green': XKCDColor(colorcode: '#8cfd7e', name: ''),
  'soft blue': XKCDColor(colorcode: '#6488ea', name: ''),
  'cerulean blue': XKCDColor(colorcode: '#056eee', name: ''),
  'golden brown': XKCDColor(colorcode: '#b27a01', name: ''),
  'bright turquoise': XKCDColor(colorcode: '#0ffef9', name: ''),
  'red pink': XKCDColor(colorcode: '#fa2a55', name: ''),
  'red purple':
      XKCDColor(colorcode: '#820747', name: 'ralcolorcodes_color_name_3004'),
  'greyish brown': XKCDColor(colorcode: '#7a6a4f', name: ''),
  'vermillion':
      XKCDColor(colorcode: '#f4320c', name: 'ralcolorcodes_color_name_2002'),
  'russet': XKCDColor(colorcode: '#a13905', name: ''),
  'steel grey': XKCDColor(colorcode: '#6f828a', name: ''),
  'lighter purple': XKCDColor(colorcode: '#a55af4', name: ''),
  'bright violet': XKCDColor(colorcode: '#ad0afd', name: ''),
  'prussian blue': XKCDColor(colorcode: '#004577', name: ''),
  'slate green': XKCDColor(colorcode: '#658d6d', name: ''),
  'dirty pink': XKCDColor(colorcode: '#ca7b80', name: ''),
  'dark blue green': XKCDColor(colorcode: '#005249', name: ''),
  'pine': XKCDColor(colorcode: '#2b5d34', name: ''),
  'yellowy green': XKCDColor(colorcode: '#bff128', name: ''),
  'dark gold': XKCDColor(colorcode: '#b59410', name: ''),
  'bluish': XKCDColor(colorcode: '#2976bb', name: ''),
  'darkish blue': XKCDColor(colorcode: '#014182', name: ''),
  'dull red': XKCDColor(colorcode: '#bb3f3f', name: ''),
  'pinky red': XKCDColor(colorcode: '#fc2647', name: ''),
  'bronze': XKCDColor(colorcode: '#a87900', name: ''),
  'pale teal': XKCDColor(colorcode: '#82cbb2', name: ''),
  'military green': XKCDColor(colorcode: '#667c3e', name: ''),
  'barbie pink': XKCDColor(colorcode: '#fe46a5', name: ''),
  'bubblegum pink': XKCDColor(colorcode: '#fe83cc', name: ''),
  'pea soup green': XKCDColor(colorcode: '#94a617', name: ''),
  'dark mustard': XKCDColor(colorcode: '#a88905', name: ''),
  'shit': XKCDColor(colorcode: '#7f5f00', name: ''),
  'medium purple': XKCDColor(colorcode: '#9e43a2', name: ''),
  'very dark green': XKCDColor(colorcode: '#062e03', name: ''),
  'dirt': XKCDColor(colorcode: '#8a6e45', name: ''),
  'dusky pink': XKCDColor(colorcode: '#cc7a8b', name: ''),
  'red violet': XKCDColor(colorcode: '#9e0168', name: ''),
  'lemon yellow':
      XKCDColor(colorcode: '#fdff38', name: 'ralcolorcodes_color_name_1012'),
  'pistachio': XKCDColor(colorcode: '#c0fa8b', name: ''),
  'dull yellow': XKCDColor(colorcode: '#eedc5b', name: ''),
  'dark lime green': XKCDColor(colorcode: '#7ebd01', name: ''),
  'denim blue': XKCDColor(colorcode: '#3b5b92', name: ''),
  'teal blue': XKCDColor(colorcode: '#01889f', name: ''),
  'lightish blue': XKCDColor(colorcode: '#3d7afd', name: ''),
  'purpley blue': XKCDColor(colorcode: '#5f34e7', name: ''),
  'light indigo': XKCDColor(colorcode: '#6d5acf', name: ''),
  'swamp green': XKCDColor(colorcode: '#748500', name: ''),
  'brown green': XKCDColor(colorcode: '#706c11', name: 'ralcolorcodes_color_name_6008'),
  'dark maroon': XKCDColor(colorcode: '#3c0008', name: ''),
  'hot purple': XKCDColor(colorcode: '#cb00f5', name: ''),
  'dark forest green': XKCDColor(colorcode: '#002d04', name: ''),
  'faded blue': XKCDColor(colorcode: '#658cbb', name: ''),
  'drab green': XKCDColor(colorcode: '#749551', name: ''),
  'light lime green': XKCDColor(colorcode: '#b9ff66', name: ''),
  'snot green': XKCDColor(colorcode: '#9dc100', name: ''),
  'yellowish': XKCDColor(colorcode: '#faee66', name: ''),
  'light blue green': XKCDColor(colorcode: '#7efbb3', name: ''),
  'bordeaux': XKCDColor(colorcode: '#7b002c', name: ''),
  'light mauve': XKCDColor(colorcode: '#c292a1', name: ''),
  'ocean': XKCDColor(colorcode: '#017b92', name: ''),
  'marigold': XKCDColor(colorcode: '#fcc006', name: ''),
  'muddy green': XKCDColor(colorcode: '#657432', name: ''),
  'dull orange': XKCDColor(colorcode: '#d8863b', name: ''),
  'steel': XKCDColor(colorcode: '#738595', name: ''),
  'electric purple': XKCDColor(colorcode: '#aa23ff', name: ''),
  'fluorescent green':
      XKCDColor(colorcode: '#08ff08', name: ''),
  'yellowish brown': XKCDColor(colorcode: '#9b7a01', name: ''),
  'blush': XKCDColor(colorcode: '#f29e8e', name: ''),
  'soft green': XKCDColor(colorcode: '#6fc276', name: ''),
  'bright orange': XKCDColor(colorcode: '#ff5b00', name: ''),
  'lemon': XKCDColor(colorcode: '#fdff52', name: ''),
  'purple grey': XKCDColor(colorcode: '#866f85', name: ''),
  'acid green': XKCDColor(colorcode: '#8ffe09', name: ''),
  'pale lavender': XKCDColor(colorcode: '#eecffe', name: ''),
  'violet blue': XKCDColor(colorcode: '#510ac9', name: ''),
  'light forest green': XKCDColor(colorcode: '#4f9153', name: ''),
  'burnt red': XKCDColor(colorcode: '#9f2305', name: ''),
  'khaki green': XKCDColor(colorcode: '#728639', name: ''),
  'cerise': XKCDColor(colorcode: '#de0c62', name: ''),
  'faded purple': XKCDColor(colorcode: '#916e99', name: ''),
  'apricot': XKCDColor(colorcode: '#ffb16d', name: ''),
  'dark olive green': XKCDColor(colorcode: '#3c4d03', name: ''),
  'grey brown': XKCDColor(colorcode: '#7f7053', name: 'ralcolorcodes_color_name_8019'),
  'green grey': XKCDColor(colorcode: '#77926f', name: 'ralcolorcodes_color_name_7009'),
  'true blue': XKCDColor(colorcode: '#010fcc', name: ''),
  'pale violet': XKCDColor(colorcode: '#ceaefa', name: ''),
  'periwinkle blue': XKCDColor(colorcode: '#8f99fb', name: ''),
  'light sky blue': XKCDColor(colorcode: '#c6fcff', name: ''),
  'blurple': XKCDColor(colorcode: '#5539cc', name: ''),
  'green brown': XKCDColor(colorcode: '#544e03', name: 'ralcolorcodes_color_name_8000'),
  'bluegreen': XKCDColor(colorcode: '#017a79', name: 'ralcolorcodes_color_name_6004'),
  'bright teal': XKCDColor(colorcode: '#01f9c6', name: ''),
  'brownish yellow': XKCDColor(colorcode: '#c9b003', name: ''),
  'pea soup': XKCDColor(colorcode: '#929901', name: ''),
  'forest': XKCDColor(colorcode: '#0b5509', name: 'forest'),
  'barney purple': XKCDColor(colorcode: '#a00498', name: ''),
  'ultramarine': XKCDColor(colorcode: '#2000b1', name: ''),
  'purplish': XKCDColor(colorcode: '#94568c', name: ''),
  'puke yellow': XKCDColor(colorcode: '#c2be0e', name: ''),
  'bluish grey': XKCDColor(colorcode: '#748b97', name: ''),
  'dark periwinkle': XKCDColor(colorcode: '#665fd1', name: ''),
  'dark lilac': XKCDColor(colorcode: '#9c6da5', name: ''),
  'reddish': XKCDColor(colorcode: '#c44240', name: ''),
  'light maroon': XKCDColor(colorcode: '#a24857', name: ''),
  'dusty purple': XKCDColor(colorcode: '#825f87', name: ''),
  'terra cotta': XKCDColor(colorcode: '#c9643b', name: ''),
  'avocado': XKCDColor(colorcode: '#90b134', name: ''),
  'marine blue': XKCDColor(colorcode: '#01386a', name: ''),
  'teal green': XKCDColor(colorcode: '#25a36f', name: ''),
  'slate grey': XKCDColor(colorcode: '#59656d', name: 'ralcolorcodes_color_name_7015'),
  'lighter green': XKCDColor(colorcode: '#75fd63', name: ''),
  'electric green': XKCDColor(colorcode: '#21fc0d', name: ''),
  'dusty blue': XKCDColor(colorcode: '#5a86ad', name: ''),
  'golden yellow':
      XKCDColor(colorcode: '#fec615', name: 'ralcolorcodes_color_name_1004'),
  'bright yellow': XKCDColor(colorcode: '#fffd01', name: ''),
  'light lavender': XKCDColor(colorcode: '#dfc5fe', name: ''),
  'umber': XKCDColor(colorcode: '#b26400', name: ''),
  'poop': XKCDColor(colorcode: '#7f5e00', name: ''),
  'dark peach': XKCDColor(colorcode: '#de7e5d', name: ''),
  'jungle green': XKCDColor(colorcode: '#048243', name: ''),
  'eggshell': XKCDColor(colorcode: '#ffffd4', name: ''),
  'denim': XKCDColor(colorcode: '#3b638c', name: ''),
  'yellow brown': XKCDColor(colorcode: '#b79400', name: ''),
  'dull purple': XKCDColor(colorcode: '#84597e', name: ''),
  'chocolate brown': XKCDColor(colorcode: '#411900', name: 'ralcolorcodes_color_name_8017'),
  'wine red':
      XKCDColor(colorcode: '#7b0323', name: 'ralcolorcodes_color_name_3005'),
  'neon blue': XKCDColor(colorcode: '#04d9ff', name: ''),
  'dirty green': XKCDColor(colorcode: '#667e2c', name: ''),
  'light tan': XKCDColor(colorcode: '#fbeeac', name: ''),
  'ice blue': XKCDColor(colorcode: '#d7fffe', name: ''),
  'cadet blue': XKCDColor(colorcode: '#4e7496', name: ''),
  'dark mauve': XKCDColor(colorcode: '#874c62', name: ''),
  'very light blue': XKCDColor(colorcode: '#d5ffff', name: ''),
  'grey purple': XKCDColor(colorcode: '#826d8c', name: ''),
  'pastel pink': XKCDColor(colorcode: '#ffbacd', name: ''),
  'very light green': XKCDColor(colorcode: '#d1ffbd', name: ''),
  'dark sky blue': XKCDColor(colorcode: '#448ee4', name: ''),
  'evergreen': XKCDColor(colorcode: '#05472a', name: ''),
  'dull pink': XKCDColor(colorcode: '#d5869d', name: ''),
  'aubergine': XKCDColor(colorcode: '#3d0734', name: ''),
  'mahogany': XKCDColor(colorcode: '#4a0100', name: ''),
  'reddish orange': XKCDColor(colorcode: '#f8481c', name: ''),
  'deep green': XKCDColor(colorcode: '#02590f', name: ''),
  'vomit green': XKCDColor(colorcode: '#89a203', name: ''),
  'purple pink': XKCDColor(colorcode: '#e03fd8', name: 'purple pink'),
  'dusty pink': XKCDColor(colorcode: '#d58a94', name: ''),
  'faded green': XKCDColor(colorcode: '#7bb274', name: ''),
  'camo green': XKCDColor(colorcode: '#526525', name: ''),
  'pinky purple': XKCDColor(colorcode: '#c94cbe', name: ''),
  'pink purple': XKCDColor(colorcode: '#db4bda', name: ''),
  'brownish red': XKCDColor(colorcode: '#9e3623', name: ''),
  'dark rose': XKCDColor(colorcode: '#b5485d', name: ''),
  'mud': XKCDColor(colorcode: '#735c12', name: ''),
  'brownish': XKCDColor(colorcode: '#9c6d57', name: ''),
  'emerald green': XKCDColor(colorcode: '#028f1e', name: 'ralcolorcodes_color_name_6001'),
  'pale brown': XKCDColor(colorcode: '#b1916e', name: 'ralcolorcodes_color_name_8025'),
  'dull blue': XKCDColor(colorcode: '#49759c', name: ''),
  'burnt umber': XKCDColor(colorcode: '#a0450e', name: ''),
  'medium green': XKCDColor(colorcode: '#39ad48', name: ''),
  'clay': XKCDColor(colorcode: '#b66a50', name: ''),
  'light aqua': XKCDColor(colorcode: '#8cffdb', name: ''),
  'light olive green': XKCDColor(colorcode: '#a4be5c', name: ''),
  'brownish orange': XKCDColor(colorcode: '#cb7723', name: ''),
  'dark aqua': XKCDColor(colorcode: '#05696b', name: ''),
  'purplish pink': XKCDColor(colorcode: '#ce5dae', name: ''),
  'dark salmon': XKCDColor(colorcode: '#c85a53', name: ''),
  'greenish grey': XKCDColor(colorcode: '#96ae8d', name: ''),
  'jade': XKCDColor(colorcode: '#1fa774', name: ''),
  'ugly green': XKCDColor(colorcode: '#7a9703', name: ''),
  'dark beige': XKCDColor(colorcode: '#ac9362', name: ''),
  'emerald': XKCDColor(colorcode: '#01a049', name: ''),
  'pale red': XKCDColor(colorcode: '#d9544d', name: ''),
  'light magenta': XKCDColor(colorcode: '#fa5ff7', name: ''),
  'sky': XKCDColor(colorcode: '#82cafc', name: ''),
  'light cyan': XKCDColor(colorcode: '#acfffc', name: ''),
  'yellow orange': XKCDColor(colorcode: '#fcb001', name: 'ralcolorcodes_color_name_2000'),
  'reddish purple': XKCDColor(colorcode: '#910951', name: ''),
  'reddish pink': XKCDColor(colorcode: '#fe2c54', name: ''),
  'orchid': XKCDColor(colorcode: '#c875c4', name: ''),
  'dirty yellow': XKCDColor(colorcode: '#cdc50a', name: ''),
  'orange red': XKCDColor(colorcode: '#fd411e', name: ''),
  'deep red': XKCDColor(colorcode: '#9a0200', name: ''),
  'orange brown': XKCDColor(colorcode: '#be6400', name: 'ralcolorcodes_color_name_8023'),
  'cobalt blue': XKCDColor(colorcode: '#030aa7', name: 'ralcolorcodes_color_name_5013'),
  'neon pink': XKCDColor(colorcode: '#fe019a', name: ''),
  'rose pink': XKCDColor(colorcode: '#f7879a', name: ''),
  'greyish purple': XKCDColor(colorcode: '#887191', name: ''),
  'raspberry': XKCDColor(colorcode: '#b00149', name: ''),
  'aqua green': XKCDColor(colorcode: '#12e193', name: ''),
  'salmon pink':
      XKCDColor(colorcode: '#fe7b7c', name: 'ralcolorcodes_color_name_3022'),
  'tangerine': XKCDColor(colorcode: '#ff9408', name: ''),
  'brownish green': XKCDColor(colorcode: '#6a6e09', name: ''),
  'red brown': XKCDColor(colorcode: '#8b2e16', name: 'ralcolorcodes_color_name_8012'),
  'greenish brown': XKCDColor(colorcode: '#696112', name: ''),
  'pumpkin': XKCDColor(colorcode: '#e17701', name: ''),
  'pine green': XKCDColor(colorcode: '#0a481e', name: 'ralcolorcodes_color_name_6028'),
  'charcoal': XKCDColor(colorcode: '#343837', name: ''),
  'baby pink': XKCDColor(colorcode: '#ffb7ce', name: ''),
  'cornflower': XKCDColor(colorcode: '#6a79f7', name: ''),
  'blue violet': XKCDColor(colorcode: '#5d06e9', name: ''),
  'chocolate': XKCDColor(colorcode: '#3d1c02', name: ''),
  'greyish green': XKCDColor(colorcode: '#82a67d', name: ''),
  'scarlet': XKCDColor(colorcode: '#be0119', name: ''),
  'green yellow': XKCDColor(colorcode: '#c9ff27', name: ''),
  'dark olive': XKCDColor(colorcode: '#373e02', name: ''),
  'sienna': XKCDColor(colorcode: '#a9561e', name: ''),
  'pastel purple': XKCDColor(colorcode: '#caa0ff', name: ''),
  'terracotta': XKCDColor(colorcode: '#ca6641', name: ''),
  'aqua blue': XKCDColor(colorcode: '#02d8e9', name: ''),
  'sage green': XKCDColor(colorcode: '#88b378', name: ''),
  'blood red': XKCDColor(colorcode: '#980002', name: ''),
  'deep pink': XKCDColor(colorcode: '#cb0162', name: ''),
  'grass': XKCDColor(colorcode: '#5cac2d', name: ''),
  'moss': XKCDColor(colorcode: '#769958', name: 'moss'),
  'pastel blue': XKCDColor(colorcode: '#a2bffe', name: 'ralcolorcodes_color_name_5024'),
  'bluish green': XKCDColor(colorcode: '#10a674', name: ''),
  'green blue': XKCDColor(colorcode: '#06b48b', name: 'ralcolorcodes_color_name_5001'),
  'dark tan': XKCDColor(colorcode: '#af884a', name: ''),
  'greenish blue': XKCDColor(colorcode: '#0b8b87', name: ''),
  'pale orange': XKCDColor(colorcode: '#ffa756', name: ''),
  'vomit': XKCDColor(colorcode: '#a2a415', name: ''),
  'forrest green': XKCDColor(colorcode: '#154406', name: ''),
  'dark lavender': XKCDColor(colorcode: '#856798', name: ''),
  'dark violet': XKCDColor(colorcode: '#34013f', name: ''),
  'purple blue': XKCDColor(colorcode: '#632de9', name: ''),
  'dark cyan': XKCDColor(colorcode: '#0a888a', name: 'common_color_dark_cyan'),
  'olive drab': XKCDColor(colorcode: '#6f7632', name: 'ralcolorcodes_color_name_6022'),
  'pinkish': XKCDColor(colorcode: '#d46a7e', name: ''),
  'cobalt': XKCDColor(colorcode: '#1e488f', name: ''),
  'neon purple': XKCDColor(colorcode: '#bc13fe', name: ''),
  'light turquoise': XKCDColor(colorcode: '#7ef4cc', name: ''),
  'apple green': XKCDColor(colorcode: '#76cd26', name: ''),
  'dull green': XKCDColor(colorcode: '#74a662', name: ''),
  'wine': XKCDColor(colorcode: '#80013f', name: ''),
  'powder blue': XKCDColor(colorcode: '#b1d1fc', name: ''),
  'off white': XKCDColor(colorcode: '#ffffe4', name: ''),
  'electric blue': XKCDColor(colorcode: '#0652ff', name: ''),
  'dark turquoise': XKCDColor(colorcode: '#045c5a', name: ''),
  'blue purple': XKCDColor(colorcode: '#5729ce', name: ''),
  'azure': XKCDColor(colorcode: '#069af3', name: ''),
  'bright red': XKCDColor(colorcode: '#ff000d', name: ''),
  'pinkish red': XKCDColor(colorcode: '#f10c45', name: ''),
  'cornflower blue': XKCDColor(colorcode: '#5170d7', name: ''),
  'light olive': XKCDColor(colorcode: '#acbf69', name: ''),
  'grape': XKCDColor(colorcode: '#6c3461', name: ''),
  'greyish blue': XKCDColor(colorcode: '#5e819d', name: ''),
  'purplish blue': XKCDColor(colorcode: '#601ef9', name: ''),
  'yellowish green': XKCDColor(colorcode: '#b0dd16', name: ''),
  'greenish yellow': XKCDColor(colorcode: '#cdfd02', name: ''),
  'medium blue': XKCDColor(colorcode: '#2c6fbb', name: ''),
  'dusty rose': XKCDColor(colorcode: '#c0737a', name: ''),
  'light violet': XKCDColor(colorcode: '#d6b4fc', name: ''),
  'midnight blue': XKCDColor(colorcode: '#020035', name: ''),
  'bluish purple': XKCDColor(colorcode: '#703be7', name: ''),
  'red orange':
      XKCDColor(colorcode: '#fd3c06', name: 'ralcolorcodes_color_name_2001'),
  'dark magenta':
      XKCDColor(colorcode: '#960056', name: 'common_color_dark_magenta'),
  'greenish': XKCDColor(colorcode: '#40a368', name: ''),
  'ocean blue': XKCDColor(colorcode: '#03719c', name: 'ralcolorcodes_color_name_5020'),
  'coral': XKCDColor(colorcode: '#fc5a50', name: ''),
  'cream': XKCDColor(colorcode: '#ffffc2', name: 'ralcolorcodes_color_name_9001'),
  'reddish brown': XKCDColor(colorcode: '#7f2b0a', name: ''),
  'burnt sienna': XKCDColor(colorcode: '#b04e0f', name: ''),
  'brick': XKCDColor(colorcode: '#a03623', name: ''),
  'sage': XKCDColor(colorcode: '#87ae73', name: ''),
  'grey green': XKCDColor(colorcode: '#789b73', name: ''),
  'white': XKCDColor(colorcode: '#ffffff', name: 'common_color_white'),
  'robins egg blue': XKCDColor(colorcode: '#98eff9', name: 'robinlue'),
  'moss green': XKCDColor(colorcode: '#658b38', name: 'ralcolorcodes_color_name_6005'),
  'steel blue': XKCDColor(colorcode: '#5a7d9a', name: 'ralcolorcodes_color_name_5011'),
  'eggplant': XKCDColor(colorcode: '#380835', name: ''),
  'light yellow':
      XKCDColor(colorcode: '#fffe7a', name: 'common_color_light_yellow'),
  'leaf green': XKCDColor(colorcode: '#5ca904', name: 'ralcolorcodes_color_name_6002'),
  'light grey':
      XKCDColor(colorcode: '#d8dcd6', name: 'ralcolorcodes_color_name_7035'),
  'puke': XKCDColor(colorcode: '#a5a502', name: ''),
  'pinkish purple': XKCDColor(colorcode: '#d648d7', name: ''),
  'sea blue': XKCDColor(colorcode: '#047495', name: ''),
  'pale purple': XKCDColor(colorcode: '#b790d4', name: ''),
  'slate blue': XKCDColor(colorcode: '#5b7c99', name: ''),
  'blue grey': XKCDColor(colorcode: '#607c8e', name: 'ralcolorcodes_color_name_7031'),
  'hunter green': XKCDColor(colorcode: '#0b4008', name: ''),
  'fuchsia': XKCDColor(colorcode: '#ed0dd9', name: ''),
  'crimson': XKCDColor(colorcode: '#8c000f', name: ''),
  'pale yellow': XKCDColor(colorcode: '#ffff84', name: ''),
  'ochre': XKCDColor(colorcode: '#bf9005', name: ''),
  'mustard yellow': XKCDColor(colorcode: '#d2bd0a', name: ''),
  'light red': XKCDColor(colorcode: '#ff474c', name: 'common_color_light_red'),
  'cerulean': XKCDColor(colorcode: '#0485d1', name: ''),
  'pale pink': XKCDColor(colorcode: '#ffcfdc', name: ''),
  'deep blue': XKCDColor(colorcode: '#040273', name: ''),
  'rust': XKCDColor(colorcode: '#a83c09', name: ''),
  'light teal': XKCDColor(colorcode: '#90e4c1', name: ''),
  'slate': XKCDColor(colorcode: '#516572', name: ''),
  'goldenrod': XKCDColor(colorcode: '#fac205', name: ''),
  'dark yellow': XKCDColor(colorcode: '#d5b60a', name: ''),
  'dark grey': XKCDColor(colorcode: '#363737', name: 'common_color_dark_rey'),
  'army green': XKCDColor(colorcode: '#4b5d16', name: ''),
  'grey blue': XKCDColor(colorcode: '#6b8ba4', name: 'ralcolorcodes_color_name_5008'),
  'seafoam': XKCDColor(colorcode: '#80f9ad', name: ''),
  'puce': XKCDColor(colorcode: '#a57e52', name: ''),
  'spring green': XKCDColor(colorcode: '#a9f971', name: ''),
  'dark orange':
      XKCDColor(colorcode: '#c65102', name: 'common_color_dark_orange'),
  'sand': XKCDColor(colorcode: '#e2ca76', name: ''),
  'pastel green': XKCDColor(colorcode: '#b0ff9d', name: 'ralcolorcodes_color_name_6019'),
  'mint': XKCDColor(colorcode: '#9ffeb0', name: ''),
  'light orange':
      XKCDColor(colorcode: '#fdaa48', name: 'common_color_light_orange'),
  'bright pink': XKCDColor(colorcode: '#fe01b1', name: ''),
  'chartreuse': XKCDColor(colorcode: '#c1f80a', name: ''),
  'deep purple': XKCDColor(colorcode: '#36013f', name: ''),
  'dark brown':
      XKCDColor(colorcode: '#341c02', name: 'common_color_dark_brown'),
  'taupe': XKCDColor(colorcode: '#b9a281', name: ''),
  'pea green': XKCDColor(colorcode: '#8eab12', name: ''),
  'puke green': XKCDColor(colorcode: '#9aae07', name: ''),
  'kelly green': XKCDColor(colorcode: '#02ab2e', name: ''),
  'seafoam green': XKCDColor(colorcode: '#7af9ab', name: ''),
  'blue green': XKCDColor(colorcode: '#137e6d', name: 'ralcolorcodes_color_name_6004'),
  'khaki': XKCDColor(colorcode: '#aaa662', name: ''),
  'burgundy': XKCDColor(colorcode: '#610023', name: ''),
  'dark teal': XKCDColor(colorcode: '#014d4e', name: ''),
  'brick red': XKCDColor(colorcode: '#8f1402', name: ''),
  'royal purple': XKCDColor(colorcode: '#4b006e', name: ''),
  'plum': XKCDColor(colorcode: '#580f41', name: ''),
  'mint green': XKCDColor(colorcode: '#8fff9f', name: 'ralcolorcodes_color_name_6029'),
  'gold': XKCDColor(colorcode: '#dbb40c', name: 'common_color_gold'),
  'baby blue': XKCDColor(colorcode: '#a2cffe', name: ''),
  'yellow green': XKCDColor(colorcode: '#c0fb2d', name: ''),
  'bright purple': XKCDColor(colorcode: '#be03fd', name: ''),
  'dark red': XKCDColor(colorcode: '#840000', name: 'common_color_dark_red'),
  'pale blue': XKCDColor(colorcode: '#d0fefe', name: ''),
  'grass green': XKCDColor(colorcode: '#3f9b0b', name: 'ralcolorcodes_color_name_6010'),
  'navy': XKCDColor(colorcode: '#01153e', name: 'navy'),
  'aquamarine': XKCDColor(colorcode: '#04d8b2', name: ''),
  'burnt orange': XKCDColor(colorcode: '#c04e01', name: ''),
  'neon green': XKCDColor(colorcode: '#0cff0c', name: ''),
  'bright blue': XKCDColor(colorcode: '#0165fc', name: ''),
  'rose':
      XKCDColor(colorcode: '#cf6275', name: 'ralcolorcodes_color_name_3017'),
  'light pink':
      XKCDColor(colorcode: '#ffd1df', name: 'ralcolorcodes_color_name_3015'),
  'mustard': XKCDColor(colorcode: '#ceb301', name: ''),
  'indigo': XKCDColor(colorcode: '#380282', name: ''),
  'lime': XKCDColor(colorcode: '#aaff32', name: ''),
  'sea green': XKCDColor(colorcode: '#53fca1', name: ''),
  'periwinkle': XKCDColor(colorcode: '#8e82fe', name: ''),
  'dark pink': XKCDColor(colorcode: '#cb416b', name: ''),
  'olive green': XKCDColor(colorcode: '#677a04', name: 'ralcolorcodes_color_name_6003'),
  'peach': XKCDColor(colorcode: '#ffb07c', name: ''),
  'pale green': XKCDColor(colorcode: '#c7fdb5', name: 'ralcolorcodes_color_name_6021'),
  'light brown':
      XKCDColor(colorcode: '#ad8150', name: 'common_color_light_brown'),
  'hot pink': XKCDColor(colorcode: '#ff028d', name: ''),
  'black': XKCDColor(colorcode: '#000000', name: 'common_color_black'),
  'lilac': XKCDColor(colorcode: '#cea2fd', name: ''),
  'navy blue': XKCDColor(colorcode: '#001146', name: ''),
  'royal blue': XKCDColor(colorcode: '#0504aa', name: ''),
  'beige':
      XKCDColor(colorcode: '#e6daa6', name: 'ralcolorcodes_color_name_1001'),
  'salmon': XKCDColor(colorcode: '#ff796c', name: ''),
  'olive': XKCDColor(colorcode: '#6e750e', name: ''),
  'maroon': XKCDColor(colorcode: '#650021', name: ''),
  'bright green': XKCDColor(colorcode: '#01ff07', name: ''),
  'dark purple':
      XKCDColor(colorcode: '#35063e', name: 'common_color_dark_purple'),
  'mauve': XKCDColor(colorcode: '#ae7181', name: 'mave'),
  'forest green': XKCDColor(colorcode: '#06470c', name: ''),
  'aqua': XKCDColor(colorcode: '#13eac9', name: ''),
  'cyan': XKCDColor(colorcode: '#00ffff', name: 'common_color_cyan'),
  'tan': XKCDColor(colorcode: '#d1b26f', name: ''),
  'dark blue': XKCDColor(colorcode: '#00035b', name: 'common_color_dark_blue'),
  'lavender': XKCDColor(colorcode: '#c79fef', name: ''),
  'turquoise': XKCDColor(colorcode: '#06c2ac', name: 'common_color_turquoise'),
  'dark green':
      XKCDColor(colorcode: '#033500', name: 'common_color_dark_green'),
  'violet': XKCDColor(colorcode: '#9a0eea', name: 'common_color_violet'),
  'light purple':
      XKCDColor(colorcode: '#bf77f6', name: 'common_color_light_purple'),
  'lime green': XKCDColor(colorcode: '#89fe05', name: ''),
  'grey': XKCDColor(colorcode: '#929591', name: 'common_color_grey'),
  'sky blue': XKCDColor(colorcode: '#75bbfd', name: 'ralcolorcodes_color_name_5015'),
  'yellow': XKCDColor(colorcode: '#ffff14', name: 'common_color_yellow'),
  'magenta': XKCDColor(colorcode: '#c20078', name: 'common_color_magenta'),
  'light green':
      XKCDColor(colorcode: '#96f97b', name: 'common_color_light_green'),
  'orange': XKCDColor(colorcode: '#f97306', name: 'common_color_orange'),
  'teal': XKCDColor(colorcode: '#029386', name: ''),
  'light blue':
      XKCDColor(colorcode: '#95d0fc', name: 'ralcolorcodes_color_name_5012'),
  'red': XKCDColor(colorcode: '#e50000', name: 'common_color_red'),
  'brown': XKCDColor(colorcode: '#653700', name: 'common_color_brown'),
  'pink': XKCDColor(colorcode: '#ff81c0', name: 'common_color_pink'),
  'blue': XKCDColor(colorcode: '#0343df', name: 'common_color_blue'),
  'green': XKCDColor(colorcode: '#15b01a', name: 'common_color_green'),
  'purple': XKCDColor(colorcode: '#7e1e9c', name: 'common_color_purple'),
};

MapEntry<String, XKCDColor>? _xkcdByRGB(RGB rgb) {
  var hexCode = HexCode.fromRGB(rgb);
  return XKCD_COLOR_CODES.entries.firstWhereOrNull((element) =>
      element.value.colorcode.toLowerCase() ==
      hexCode.toString().toLowerCase());
}

Map<String, XKCDColor> findSimilarXKCDColors(RGB rgb) {
  var xkcd = _xkcdByRGB(rgb);
  if (xkcd != null) {
    return Map<String, XKCDColor>.fromEntries(
        xkcd as Iterable<MapEntry<String, XKCDColor>>);
  }

  var XKCDRGBs = XKCD_COLOR_CODES.values
      .map((xkcd) => HexCode(xkcd.colorcode).toRGB())
      .toList();

  var out = <String, XKCDColor>{};
  var distance = 0;
  while (distance < 100) {
    distance++;
    var nearestRGBs = findNearestRGBs(rgb, XKCDRGBs, distance: distance);

    if (nearestRGBs.length >= 5) {
      for (var nearestRGB in nearestRGBs) {
        var nearestRAL = _xkcdByRGB(nearestRGB);
        if (nearestRAL != null) out.addAll({nearestRAL.key: nearestRAL.value});
      }
      return out;
    }
  }

  return out;
}
