part of 'package:gc_wizard/tools/images_and_files/waveform/logic/id3_chunk.dart';

class _ID3v4extendedHeader{
  final String header;
  final bool extHeaderB;
  final bool extHeaderC;
  final bool extHeaderD;

  _ID3v4extendedHeader(this.header, this.extHeaderB, this.extHeaderC, this.extHeaderD);
}
enum ID3v3FLAGS { UNSYNCHRONISATION, EXTENDED_HEADER, EXPERIMENTAL_TAGS }

final Map<String, String> _ID3_FRAMES = {
  'AENC': 'Audio encryption',
  'APIC': 'Attached picture',
  'COMM': 'Comments',
  'COMR': 'Commercial frame',
  'ENCR': 'Encryption method registration',
  'EQUA': 'Equalization',
  'ETCO': 'Event timing codes',
  'GEOB': 'General encapsulated object',
  'GRID': 'Group identificationtion',
  'IPLS': 'Involved people list',
  'LINK': 'Linked information',
  'MCDI': 'Music CD identifier',
  'MLLT': 'MPEG location lookup table',
  'OWNE': 'Ownership frame',
  'PRIV': 'Private frame',
  'PCNT': 'Play counter',
  'POPM': 'Popularimeter',
  'POSS': 'Position synchronisation frame',
  'RBUF': 'Recommended buffer size',
  'RVAD': 'Relative volume adjustment',
  'RVRB': 'Reverb',
  'SYLT': 'Synchronized lyric/text',
  'SYTC': 'Synchronized tempo codes',
  'TALB': 'Album/Movie/Show title',
  'TBPM': 'BPM (beats per minute)',
  'TCOM': 'Composer',
  'TCON': 'Content type',
  'TCOP': 'Copyright message',
  'TDAT': 'Date',
  'TDLY': 'Playlist delay',
  'TENC': 'Encoded by',
  'TEXT': 'Lyricist/Text writer',
  'TFLT': 'File type',
  'TIME': 'Time',
  'TIT1': 'Content group description',
  'TIT2': 'Title/songname/content ion',
  'TIT3': 'Subtitle/Description refinement',
  'TKEY': 'Initial key',
  'TLAN': 'Language(s)',
  'TLEN': 'Length',
  'TMED': 'Media type',
  'TOAL': 'Original album/movie/show title',
  'TOFN': 'Original filename',
  'TOLY': 'Original lyricist(s)/text',
  'TOPE': 'Original artist(s)/performer(s)',
  'TORY': 'Original release year',
  'TOWN': 'File owner/licensee',
  'TPE1': 'Lead performer(s)/Soloist(s)',
  'TPE2': 'Band/orchestra/accompaniment',
  'TPE3': 'Conductor/performer refinement',
  'TPE4': 'Interpreted, remixed, or otherwise modified by',
  'TPOS': 'Part of a set',
  'TPUB': 'Publisher',
  'TRCK': 'Track number/Position in set',
  'TRDA': 'Recording dates',
  'TRSN': 'Internet radio station name',
  'TRSO': 'Internet radio station owner',
  'TSIZ': 'Size',
  'TSRC': 'ISRC (international standard g code)',
  'TSSE': 'Software/Hardware and settings  encoding',
  'TYER': 'Year',
  'TXXX': 'User defined text information',
  'UFID': 'Unique file identifier',
  'USER': 'Terms of use',
  'USLT': 'Unsychronized lyric/text transcription',
  'WCOM': 'Commercial information',
  'WCOP': 'Copyright/Legal information',
  'WOAF': 'Official audio file webpage',
  'WOAR': 'Official artist/performer webpage',
  'WOAS': 'Official audio source webpage',
  'WORS': 'Official internet radio station',
  'WPAY': 'Payment',
  'WPUB': 'Publishers official webpage',
  'WXXX': 'User defined URL link frame',
};

final List<String> _ID3_TEXT_FRAMES = [
  'TALB',
  'TBPM',
  'TCOM',
  'TCON',
  'TCOP',
  'TDAT',
  'TDLY',
  'TENC',
  'TEXT',
  'TFLT',
  'TIME',
  'TIT1',
  'TIT2',
  'TIT3',
  'TKEY',
  'TLAN',
  'TLEN',
  'TMED',
  'TOAL',
  'TOFN',
  'TOLY',
  'TOPE',
  'TORY',
  'TOWN',
  'TPE1',
  'TPE2',
  'TPE3',
  'TPE4',
  'TPOS',
  'TPUB',
  'TRCK',
  'TRDA',
  'TRSN',
  'TRSO',
  'TSIZ',
  'TSRC',
  'TSSE',
  'TYER',
  'TXXX',
];


